function [bc_J,bc_Jd] = BackJacobian(in1)
%BACKJACOBIAN
%    [BC_J,BC_JD] = BACKJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Jan-2020 18:02:32

q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
qd3 = in1(10,:);
qd6 = in1(13,:);
qd7 = in1(14,:);
t2 = cos(q3);
t3 = cos(q6);
t4 = sin(q7);
t5 = cos(q7);
t6 = sin(q6);
t7 = sin(q3);
t8 = t3.*t5;
t14 = t4.*t6;
t9 = t8-t14;
t10 = t3.*t4;
t11 = t5.*t6;
t12 = t10+t11;
t13 = t7.*t12.*(3.9e1./2.0e2);
t15 = t6.*(2.09e2./1.0e3);
t16 = t15+1.9e1./1.0e2;
t17 = t3.*t7.*(2.09e2./1.0e3);
t18 = t2.*t12.*(3.9e1./2.0e2);
t19 = t7.*t9.*(3.9e1./2.0e2);
t20 = t2.*t16;
t21 = t17+t18+t19+t20;
t22 = t18+t19;
t23 = t2.*t6.*(2.09e2./1.0e3);
t24 = t17+t18+t19+t23;
t25 = qd7.*t22;
t26 = qd6.*t24;
t27 = t7.*t16;
t29 = t2.*t9.*(3.9e1./2.0e2);
t30 = t2.*t3.*(2.09e2./1.0e3);
t28 = t13+t27-t29-t30;
t31 = t6.*t7.*(2.09e2./1.0e3);
bc_J = reshape([1.0,0.0,0.0,1.0,t28,t21,0.0,0.0,0.0,0.0,t13+t31-t2.*t3.*(2.09e2./1.0e3)-t2.*t9.*(3.9e1./2.0e2),t24,t13-t2.*t9.*(3.9e1./2.0e2),t22],[2,7]);
if nargout > 1
    t32 = t13-t29;
    t33 = t13-t29-t30+t31;
    bc_Jd = reshape([0.0,0.0,0.0,0.0,t25+t26+qd3.*t21,-qd3.*t28-qd6.*t33-qd7.*t32,0.0,0.0,0.0,0.0,t25+t26+qd3.*t24,-qd3.*t33-qd6.*t33-qd7.*t32,t25+qd3.*t22+qd6.*t22,-qd3.*t32-qd6.*t32-qd7.*t32],[2,7]);
end
