function [ft_J,ft_Jd] = FrontJacobian(in1)
%FRONTJACOBIAN
%    [FT_J,FT_JD] = FRONTJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Jan-2020 18:02:31

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
qd3 = in1(10,:);
qd4 = in1(11,:);
qd5 = in1(12,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = sin(q5);
t5 = cos(q5);
t6 = sin(q4);
t7 = sin(q3);
t8 = t3.*t5;
t14 = t4.*t6;
t9 = t8-t14;
t10 = t3.*t4;
t11 = t5.*t6;
t12 = t10+t11;
t13 = t7.*t12.*(3.9e1./2.0e2);
t15 = t6.*(2.09e2./1.0e3);
t16 = t15-1.9e1./1.0e2;
t17 = t3.*t7.*(2.09e2./1.0e3);
t18 = t2.*t12.*(3.9e1./2.0e2);
t19 = t7.*t9.*(3.9e1./2.0e2);
t20 = t2.*t16;
t21 = t17+t18+t19+t20;
t22 = t18+t19;
t23 = t2.*t6.*(2.09e2./1.0e3);
t24 = t17+t18+t19+t23;
t25 = qd5.*t22;
t26 = qd4.*t24;
t27 = t7.*t16;
t29 = t2.*t9.*(3.9e1./2.0e2);
t30 = t2.*t3.*(2.09e2./1.0e3);
t28 = t13+t27-t29-t30;
t31 = t6.*t7.*(2.09e2./1.0e3);
ft_J = reshape([1.0,0.0,0.0,1.0,t28,t21,t13+t31-t2.*t3.*(2.09e2./1.0e3)-t2.*t9.*(3.9e1./2.0e2),t24,t13-t2.*t9.*(3.9e1./2.0e2),t22,0.0,0.0,0.0,0.0],[2,7]);
if nargout > 1
    t32 = t13-t29;
    t33 = t13-t29-t30+t31;
    ft_Jd = reshape([0.0,0.0,0.0,0.0,t25+t26+qd3.*t21,-qd3.*t28-qd4.*t33-qd5.*t32,t25+t26+qd3.*t24,-qd3.*t33-qd4.*t33-qd5.*t32,t25+qd3.*t22+qd4.*t22,-qd3.*t32-qd4.*t32-qd5.*t32,0.0,0.0,0.0,0.0],[2,7]);
end
