/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

extern "C" int bc_dyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int bc_dyn_alloc_mem(void);
extern "C" int bc_dyn_init_mem(int mem);
extern "C" void bc_dyn_free_mem(int mem);
extern "C" int bc_dyn_checkout(void);
extern "C" void bc_dyn_release(int mem);
extern "C" void bc_dyn_incref(void);
extern "C" void bc_dyn_decref(void);
extern "C" casadi_int bc_dyn_n_out(void);
extern "C" casadi_int bc_dyn_n_in(void);
extern "C" casadi_real bc_dyn_default_in(casadi_int i);
extern "C" const char* bc_dyn_name_in(casadi_int i);
extern "C" const char* bc_dyn_name_out(casadi_int i);
extern "C" const casadi_int* bc_dyn_sparsity_in(casadi_int i);
extern "C" const casadi_int* bc_dyn_sparsity_out(casadi_int i);
extern "C" int bc_dyn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
