/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BckJac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[11] = {4, 4, 0, 2, 2, 4, 4, 0, 2, 0, 2};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[9] = {4, 4, 0, 0, 0, 0, 2, 0, 2};
static const casadi_int casadi_s3[9] = {4, 4, 0, 1, 1, 2, 2, 3, 3};
static const casadi_int casadi_s4[7] = {2, 2, 0, 0, 2, 0, 1};
static const casadi_int casadi_s5[7] = {2, 2, 0, 1, 2, 1, 1};
static const casadi_int casadi_s6[18] = {2, 7, 0, 1, 2, 4, 4, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s7[13] = {7, 2, 0, 4, 8, 0, 2, 5, 6, 1, 2, 5, 6};
static const casadi_int casadi_s8[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_c0[4] = {0., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {0., 1., 0., 0.};
static const casadi_real casadi_c2[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.9000000000000000e-001, 0., 0., 1.};
static const casadi_real casadi_c3[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., -2.0899999999999999e-001, 1.};
static const casadi_real casadi_c4[4] = {0., 0., -1.9500000000000001e-001, 1.};
static const casadi_real casadi_c5[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., -1.9000000000000000e-001, 0., 0., 1.};

/* BckJac:(i0[14])->(o0[2x7,8nz],o1[2x7,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+12, *w2=w+16, *w3=w+32, w4, w5, w6, *w7=w+51, w8, *w9=w+59, *w10=w+63, *w11=w+67, *w12=w+71, *w13=w+75, *w14=w+91, w15, *w16=w+108, *w17=w+124, *w18=w+140, *w19=w+156, w20, *w21=w+173, *w22=w+189, *w25=w+205, *w27=w+207, *w28=w+209, w29, *w30=w+226, *w31=w+230, *w33=w+246, *w34=w+262, *w35=w+265, *w36=w+281, *w37=w+297, w38, *w39=w+314, *w40=w+318, *w41=w+334, w42, *w43=w+351, *w44=w+354, *w45=w+360, *w46=w+362, *w47=w+378, *w48=w+394, *w49=w+410, *w50=w+418, *w51=w+434, *w52=w+438, *w53=w+454, *w54=w+470, *w55=w+486;
  /* #0: @0 = zeros(7x2,8nz) */
  casadi_clear(w0, 8);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #3: @3 = zeros(4x4) */
  casadi_clear(w3, 16);
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = 0 */
  w5 = 0.;
  /* #6: @6 = 0 */
  w6 = 0.;
  /* #7: @7 = input[0][0] */
  casadi_copy(arg[0], 7, w7);
  /* #8: @8 = @7[0] */
  for (rr=(&w8), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #9: @9 = horzcat(@4, @5, @6, @8) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  /* #10: @9 = @9' */
  /* #11: @4 = 0 */
  w4 = 0.;
  /* #12: @5 = 1 */
  w5 = 1.;
  /* #13: @6 = 0 */
  w6 = 0.;
  /* #14: @8 = 0 */
  w8 = 0.;
  /* #15: @10 = horzcat(@4, @5, @6, @8) */
  rr=w10;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  /* #16: @10 = @10' */
  /* #17: @4 = 0 */
  w4 = 0.;
  /* #18: @5 = 0 */
  w5 = 0.;
  /* #19: @6 = 1 */
  w6 = 1.;
  /* #20: @8 = @7[1] */
  for (rr=(&w8), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #21: @11 = horzcat(@4, @5, @6, @8) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  /* #22: @11 = @11' */
  /* #23: @12 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w12);
  /* #24: @12 = @12' */
  /* #25: @13 = horzcat(@9, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #26: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @4 = @7[2] */
  for (rr=(&w4), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #28: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #29: @6 = 0 */
  w6 = 0.;
  /* #30: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #31: @15 = 0 */
  w15 = 0.;
  /* #32: @9 = horzcat(@5, @6, @8, @15) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w15;
  /* #33: @9 = @9' */
  /* #34: @10 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c1, 4, w10);
  /* #35: @10 = @10' */
  /* #36: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #37: @5 = (-@5) */
  w5 = (- w5 );
  /* #38: @6 = 0 */
  w6 = 0.;
  /* #39: @8 = cos(@4) */
  w8 = cos( w4 );
  /* #40: @15 = 0 */
  w15 = 0.;
  /* #41: @11 = horzcat(@5, @6, @8, @15) */
  rr=w11;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w15;
  /* #42: @11 = @11' */
  /* #43: @12 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w12);
  /* #44: @12 = @12' */
  /* #45: @13 = horzcat(@9, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #46: @16 = @13' */
  for (i=0, rr=w16, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #47: @3 = mac(@14,@16,@3) */
  for (i=0, rr=w3; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #48: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #49: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #50: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #51: @19 = 
  [[1, 0, 0, 0.19], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c2, 16, w19);
  /* #52: @5 = @7[3] */
  for (rr=(&w5), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #53: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #54: @8 = 0 */
  w8 = 0.;
  /* #55: @15 = sin(@5) */
  w15 = sin( w5 );
  /* #56: @20 = 0 */
  w20 = 0.;
  /* #57: @9 = horzcat(@6, @8, @15, @20) */
  rr=w9;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w20;
  /* #58: @9 = @9' */
  /* #59: @10 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c1, 4, w10);
  /* #60: @10 = @10' */
  /* #61: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #62: @6 = (-@6) */
  w6 = (- w6 );
  /* #63: @8 = 0 */
  w8 = 0.;
  /* #64: @15 = cos(@5) */
  w15 = cos( w5 );
  /* #65: @20 = 0 */
  w20 = 0.;
  /* #66: @11 = horzcat(@6, @8, @15, @20) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w20;
  /* #67: @11 = @11' */
  /* #68: @12 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w12);
  /* #69: @12 = @12' */
  /* #70: @21 = horzcat(@9, @10, @11, @12) */
  rr=w21;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #71: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #72: @18 = mac(@19,@22,@18) */
  for (i=0, rr=w18; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w19+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #73: @22 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, -0.209], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c3, 16, w22);
  /* #74: @17 = mac(@18,@22,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #75: @6 = @7[4] */
  for (rr=(&w6), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #76: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #77: @8 = (-@8) */
  w8 = (- w8 );
  /* #78: @23 = 00 */
  /* #79: @15 = cos(@6) */
  w15 = cos( w6 );
  /* #80: @24 = 00 */
  /* #81: @25 = horzcat(@8, @23, @15, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w15;
  /* #82: @25 = @25' */
  /* #83: @23 = zeros(4x1,0nz) */
  /* #84: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #85: @8 = (-@8) */
  w8 = (- w8 );
  /* #86: @24 = 00 */
  /* #87: @15 = sin(@6) */
  w15 = sin( w6 );
  /* #88: @15 = (-@15) */
  w15 = (- w15 );
  /* #89: @26 = 00 */
  /* #90: @27 = horzcat(@8, @24, @15, @26) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w15;
  /* #91: @27 = @27' */
  /* #92: @24 = zeros(4x1,0nz) */
  /* #93: @9 = horzcat(@25, @23, @27, @24) */
  rr=w9;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #94: @10 = @9' */
  casadi_trans(w9,casadi_s0, w10, casadi_s0, iw);
  /* #95: @13 = mac(@17,@10,@13) */
  casadi_mtimes(w17, casadi_s1, w10, casadi_s0, w13, casadi_s1, w, 0);
  /* #96: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #97: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #98: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #99: @8 = sin(@5) */
  w8 = sin( w5 );
  /* #100: @8 = (-@8) */
  w8 = (- w8 );
  /* #101: @23 = 00 */
  /* #102: @15 = cos(@5) */
  w15 = cos( w5 );
  /* #103: @24 = 00 */
  /* #104: @25 = horzcat(@8, @23, @15, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w15;
  /* #105: @25 = @25' */
  /* #106: @23 = zeros(4x1,0nz) */
  /* #107: @8 = cos(@5) */
  w8 = cos( w5 );
  /* #108: @8 = (-@8) */
  w8 = (- w8 );
  /* #109: @24 = 00 */
  /* #110: @15 = sin(@5) */
  w15 = sin( w5 );
  /* #111: @15 = (-@15) */
  w15 = (- w15 );
  /* #112: @26 = 00 */
  /* #113: @27 = horzcat(@8, @24, @15, @26) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w15;
  /* #114: @27 = @27' */
  /* #115: @24 = zeros(4x1,0nz) */
  /* #116: @9 = horzcat(@25, @23, @27, @24) */
  rr=w9;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #117: @11 = @9' */
  casadi_trans(w9,casadi_s0, w11, casadi_s0, iw);
  /* #118: @28 = mac(@19,@11,@28) */
  casadi_mtimes(w19, casadi_s1, w11, casadi_s0, w28, casadi_s1, w, 0);
  /* #119: @21 = mac(@28,@22,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #120: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #121: @15 = 0 */
  w15 = 0.;
  /* #122: @20 = sin(@6) */
  w20 = sin( w6 );
  /* #123: @29 = 0 */
  w29 = 0.;
  /* #124: @11 = horzcat(@8, @15, @20, @29) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w20;
  *rr++ = w29;
  /* #125: @11 = @11' */
  /* #126: @9 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c1, 4, w9);
  /* #127: @9 = @9' */
  /* #128: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #129: @8 = (-@8) */
  w8 = (- w8 );
  /* #130: @15 = 0 */
  w15 = 0.;
  /* #131: @20 = cos(@6) */
  w20 = cos( w6 );
  /* #132: @29 = 0 */
  w29 = 0.;
  /* #133: @12 = horzcat(@8, @15, @20, @29) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w20;
  *rr++ = w29;
  /* #134: @12 = @12' */
  /* #135: @30 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w30);
  /* #136: @30 = @30' */
  /* #137: @28 = horzcat(@11, @9, @12, @30) */
  rr=w28;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #138: @31 = @28' */
  for (i=0, rr=w31, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #139: @18 = mac(@21,@31,@18) */
  for (i=0, rr=w18; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w21+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #140: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<16; ++i) (*rr++) += (*cs++);
  /* #141: @2 = mac(@3,@13,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #142: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #143: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #144: @23 = 00 */
  /* #145: @24 = 00 */
  /* #146: @26 = 00 */
  /* #147: @8 = 1 */
  w8 = 1.;
  /* #148: @15 = horzcat(@23, @24, @26, @8) */
  rr=(&w15);
  *rr++ = w8;
  /* #149: @15 = @15' */
  /* #150: @23 = zeros(4x1,0nz) */
  /* #151: @24 = 00 */
  /* #152: @26 = 00 */
  /* #153: @32 = 00 */
  /* #154: @8 = 1 */
  w8 = 1.;
  /* #155: @20 = horzcat(@24, @26, @32, @8) */
  rr=(&w20);
  *rr++ = w8;
  /* #156: @20 = @20' */
  /* #157: @24 = zeros(4x1,0nz) */
  /* #158: @25 = horzcat(@15, @23, @20, @24) */
  rr=w25;
  *rr++ = w15;
  *rr++ = w20;
  /* #159: @27 = @25' */
  casadi_trans(w25,casadi_s3, w27, casadi_s2, iw);
  /* #160: @28 = mac(@27,@16,@28) */
  casadi_mtimes(w27, casadi_s2, w16, casadi_s1, w28, casadi_s1, w, 0);
  /* #161: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #162: @33 = mac(@17,@31,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w17+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #163: @18 = mac(@28,@33,@18) */
  for (i=0, rr=w18; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w33+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #164: @2 = (@2+@18) */
  for (i=0, rr=w2, cs=w18; i<16; ++i) (*rr++) += (*cs++);
  /* #165: @11 = [0, 0, -0.195, 1] */
  casadi_copy(casadi_c4, 4, w11);
  /* #166: @1 = mac(@2,@11,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #167: @34 = @1[:3] */
  for (rr=w34, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #168: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #169: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #170: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #171: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #172: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #173: @37 = 
  [[1, 0, 0, -0.19], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 16, w37);
  /* #174: @15 = @7[5] */
  for (rr=(&w15), ss=w7+5; ss!=w7+6; ss+=1) *rr++ = *ss;
  /* #175: @20 = cos(@15) */
  w20 = cos( w15 );
  /* #176: @8 = 0 */
  w8 = 0.;
  /* #177: @29 = sin(@15) */
  w29 = sin( w15 );
  /* #178: @38 = 0 */
  w38 = 0.;
  /* #179: @9 = horzcat(@20, @8, @29, @38) */
  rr=w9;
  *rr++ = w20;
  *rr++ = w8;
  *rr++ = w29;
  *rr++ = w38;
  /* #180: @9 = @9' */
  /* #181: @12 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c1, 4, w12);
  /* #182: @12 = @12' */
  /* #183: @20 = sin(@15) */
  w20 = sin( w15 );
  /* #184: @20 = (-@20) */
  w20 = (- w20 );
  /* #185: @8 = 0 */
  w8 = 0.;
  /* #186: @29 = cos(@15) */
  w29 = cos( w15 );
  /* #187: @38 = 0 */
  w38 = 0.;
  /* #188: @30 = horzcat(@20, @8, @29, @38) */
  rr=w30;
  *rr++ = w20;
  *rr++ = w8;
  *rr++ = w29;
  *rr++ = w38;
  /* #189: @30 = @30' */
  /* #190: @39 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w39);
  /* #191: @39 = @39' */
  /* #192: @40 = horzcat(@9, @12, @30, @39) */
  rr=w40;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  /* #193: @41 = @40' */
  for (i=0, rr=w41, cs=w40; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #194: @36 = mac(@37,@41,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w37+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #195: @41 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, -0.209], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c3, 16, w41);
  /* #196: @35 = mac(@36,@41,@35) */
  for (i=0, rr=w35; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #197: @20 = @7[6] */
  for (rr=(&w20), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #198: @8 = cos(@20) */
  w8 = cos( w20 );
  /* #199: @29 = 0 */
  w29 = 0.;
  /* #200: @38 = sin(@20) */
  w38 = sin( w20 );
  /* #201: @42 = 0 */
  w42 = 0.;
  /* #202: @9 = horzcat(@8, @29, @38, @42) */
  rr=w9;
  *rr++ = w8;
  *rr++ = w29;
  *rr++ = w38;
  *rr++ = w42;
  /* #203: @9 = @9' */
  /* #204: @12 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c1, 4, w12);
  /* #205: @12 = @12' */
  /* #206: @8 = sin(@20) */
  w8 = sin( w20 );
  /* #207: @8 = (-@8) */
  w8 = (- w8 );
  /* #208: @29 = 0 */
  w29 = 0.;
  /* #209: @38 = cos(@20) */
  w38 = cos( w20 );
  /* #210: @42 = 0 */
  w42 = 0.;
  /* #211: @30 = horzcat(@8, @29, @38, @42) */
  rr=w30;
  *rr++ = w8;
  *rr++ = w29;
  *rr++ = w38;
  *rr++ = w42;
  /* #212: @30 = @30' */
  /* #213: @39 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w39);
  /* #214: @39 = @39' */
  /* #215: @36 = horzcat(@9, @12, @30, @39) */
  rr=w36;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  /* #216: @40 = @36' */
  for (i=0, rr=w40, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #217: @18 = mac(@35,@40,@18) */
  for (i=0, rr=w18; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #218: @2 = mac(@28,@18,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #219: @9 = [0, 0, -0.195, 1] */
  casadi_copy(casadi_c4, 4, w9);
  /* #220: @1 = mac(@2,@9,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #221: @43 = @1[:3] */
  for (rr=w43, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #222: @44 = horzcat(@34, @43) */
  rr=w44;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #223: @25 = @44[:6:3] */
  for (rr=w25, ss=w44+0; ss!=w44+6; ss+=3) *rr++ = *ss;
  /* #224: @25 = @25' */
  /* #225: @45 = @44[2:8:3] */
  for (rr=w45, ss=w44+2; ss!=w44+8; ss+=3) *rr++ = *ss;
  /* #226: @45 = @45' */
  /* #227: @1 = horzcat(@25, @45) */
  rr=w1;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #228: @12 = @1' */
  for (i=0, rr=w12, cs=w1; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #229: @25 = @12[2:4] */
  for (rr=w25, ss=w12+2; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #230: (@0[:8:4] = @25) */
  for (rr=w0+0, ss=w25; rr!=w0+8; rr+=4) *rr = *ss++;
  /* #231: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #232: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #233: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #234: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #235: @8 = (-@8) */
  w8 = (- w8 );
  /* #236: @23 = 00 */
  /* #237: @29 = cos(@4) */
  w29 = cos( w4 );
  /* #238: @24 = 00 */
  /* #239: @25 = horzcat(@8, @23, @29, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w29;
  /* #240: @25 = @25' */
  /* #241: @23 = zeros(4x1,0nz) */
  /* #242: @8 = cos(@4) */
  w8 = cos( w4 );
  /* #243: @8 = (-@8) */
  w8 = (- w8 );
  /* #244: @24 = 00 */
  /* #245: @29 = sin(@4) */
  w29 = sin( w4 );
  /* #246: @29 = (-@29) */
  w29 = (- w29 );
  /* #247: @26 = 00 */
  /* #248: @45 = horzcat(@8, @24, @29, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w29;
  /* #249: @45 = @45' */
  /* #250: @24 = zeros(4x1,0nz) */
  /* #251: @1 = horzcat(@25, @23, @45, @24) */
  rr=w1;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #252: @30 = @1' */
  casadi_trans(w1,casadi_s0, w30, casadi_s0, iw);
  /* #253: @36 = mac(@14,@30,@36) */
  casadi_mtimes(w14, casadi_s1, w30, casadi_s0, w36, casadi_s1, w, 0);
  /* #254: @2 = mac(@36,@33,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w33+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #255: @12 = mac(@2,@11,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #256: @34 = @12[:3] */
  for (rr=w34, ss=w12+0; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #257: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #258: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #259: @2 = mac(@36,@18,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #260: @12 = mac(@2,@9,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #261: @43 = @12[:3] */
  for (rr=w43, ss=w12+0; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #262: @44 = horzcat(@34, @43) */
  rr=w44;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #263: @25 = @44[:6:3] */
  for (rr=w25, ss=w44+0; ss!=w44+6; ss+=3) *rr++ = *ss;
  /* #264: @25 = @25' */
  /* #265: @45 = @44[2:8:3] */
  for (rr=w45, ss=w44+2; ss!=w44+8; ss+=3) *rr++ = *ss;
  /* #266: @45 = @45' */
  /* #267: @12 = horzcat(@25, @45) */
  rr=w12;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #268: @1 = @12' */
  for (i=0, rr=w1, cs=w12; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #269: @25 = @1[2:4] */
  for (rr=w25, ss=w1+2; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #270: (@0[1:9:4] = @25) */
  for (rr=w0+1, ss=w25; rr!=w0+9; rr+=4) *rr = *ss++;
  /* #271: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #272: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #273: @46 = zeros(4x4) */
  casadi_clear(w46, 16);
  /* #274: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #275: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #276: @8 = sin(@15) */
  w8 = sin( w15 );
  /* #277: @8 = (-@8) */
  w8 = (- w8 );
  /* #278: @23 = 00 */
  /* #279: @29 = cos(@15) */
  w29 = cos( w15 );
  /* #280: @24 = 00 */
  /* #281: @25 = horzcat(@8, @23, @29, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w29;
  /* #282: @25 = @25' */
  /* #283: @23 = zeros(4x1,0nz) */
  /* #284: @8 = cos(@15) */
  w8 = cos( w15 );
  /* #285: @8 = (-@8) */
  w8 = (- w8 );
  /* #286: @24 = 00 */
  /* #287: @29 = sin(@15) */
  w29 = sin( w15 );
  /* #288: @29 = (-@29) */
  w29 = (- w29 );
  /* #289: @26 = 00 */
  /* #290: @45 = horzcat(@8, @24, @29, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w29;
  /* #291: @45 = @45' */
  /* #292: @24 = zeros(4x1,0nz) */
  /* #293: @12 = horzcat(@25, @23, @45, @24) */
  rr=w12;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #294: @39 = @12' */
  casadi_trans(w12,casadi_s0, w39, casadi_s0, iw);
  /* #295: @48 = mac(@37,@39,@48) */
  casadi_mtimes(w37, casadi_s1, w39, casadi_s0, w48, casadi_s1, w, 0);
  /* #296: @47 = mac(@48,@41,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w48+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #297: @46 = mac(@47,@40,@46) */
  for (i=0, rr=w46; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w47+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #298: @2 = mac(@3,@46,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w46+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #299: @1 = mac(@2,@9,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #300: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #301: @8 = @8' */
  /* #302: @29 = @1[2] */
  for (rr=(&w29), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #303: @29 = @29' */
  /* #304: @25 = horzcat(@8, @29) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w29;
  /* #305: @45 = @25' */
  casadi_trans(w25,casadi_s5, w45, casadi_s4, iw);
  /* #306: @25 = @45[:2] */
  for (rr=w25, ss=w45+0; ss!=w45+2; ss+=1) *rr++ = *ss;
  /* #307: (@0[2:10:4] = @25) */
  for (rr=w0+2, ss=w25; rr!=w0+10; rr+=4) *rr = *ss++;
  /* #308: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #309: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #310: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #311: @8 = sin(@20) */
  w8 = sin( w20 );
  /* #312: @8 = (-@8) */
  w8 = (- w8 );
  /* #313: @23 = 00 */
  /* #314: @29 = cos(@20) */
  w29 = cos( w20 );
  /* #315: @24 = 00 */
  /* #316: @25 = horzcat(@8, @23, @29, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w29;
  /* #317: @25 = @25' */
  /* #318: @23 = zeros(4x1,0nz) */
  /* #319: @8 = cos(@20) */
  w8 = cos( w20 );
  /* #320: @8 = (-@8) */
  w8 = (- w8 );
  /* #321: @24 = 00 */
  /* #322: @29 = sin(@20) */
  w29 = sin( w20 );
  /* #323: @29 = (-@29) */
  w29 = (- w29 );
  /* #324: @26 = 00 */
  /* #325: @45 = horzcat(@8, @24, @29, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w29;
  /* #326: @45 = @45' */
  /* #327: @24 = zeros(4x1,0nz) */
  /* #328: @39 = horzcat(@25, @23, @45, @24) */
  rr=w39;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #329: @12 = @39' */
  casadi_trans(w39,casadi_s0, w12, casadi_s0, iw);
  /* #330: @48 = mac(@35,@12,@48) */
  casadi_mtimes(w35, casadi_s1, w12, casadi_s0, w48, casadi_s1, w, 0);
  /* #331: @2 = mac(@3,@48,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #332: @1 = mac(@2,@9,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #333: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #334: @8 = @8' */
  /* #335: @29 = @1[2] */
  for (rr=(&w29), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #336: @29 = @29' */
  /* #337: @25 = horzcat(@8, @29) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w29;
  /* #338: @45 = @25' */
  casadi_trans(w25,casadi_s5, w45, casadi_s4, iw);
  /* #339: @25 = @45[:2] */
  for (rr=w25, ss=w45+0; ss!=w45+2; ss+=1) *rr++ = *ss;
  /* #340: (@0[3:11:4] = @25) */
  for (rr=w0+3, ss=w25; rr!=w0+11; rr+=4) *rr = *ss++;
  /* #341: @49 = @0' */
  casadi_trans(w0,casadi_s7, w49, casadi_s6, iw);
  /* #342: output[0][0] = @49 */
  casadi_copy(w49, 8, res[0]);
  /* #343: @49 = zeros(7x2,8nz) */
  casadi_clear(w49, 8);
  /* #344: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #345: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #346: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #347: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #348: @7 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 7, w7);
  /* #349: @29 = @7[4] */
  for (rr=(&w29), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #350: @8 = (@8*@29) */
  w8 *= w29;
  /* #351: @8 = (-@8) */
  w8 = (- w8 );
  /* #352: @23 = 00 */
  /* #353: @38 = sin(@6) */
  w38 = sin( w6 );
  /* #354: @38 = (@38*@29) */
  w38 *= w29;
  /* #355: @38 = (-@38) */
  w38 = (- w38 );
  /* #356: @24 = 00 */
  /* #357: @25 = horzcat(@8, @23, @38, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w38;
  /* #358: @25 = @25' */
  /* #359: @23 = zeros(4x1,0nz) */
  /* #360: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #361: @8 = (@8*@29) */
  w8 *= w29;
  /* #362: @24 = 00 */
  /* #363: @38 = cos(@6) */
  w38 = cos( w6 );
  /* #364: @38 = (@38*@29) */
  w38 *= w29;
  /* #365: @38 = (-@38) */
  w38 = (- w38 );
  /* #366: @26 = 00 */
  /* #367: @45 = horzcat(@8, @24, @38, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w38;
  /* #368: @45 = @45' */
  /* #369: @24 = zeros(4x1,0nz) */
  /* #370: @39 = horzcat(@25, @23, @45, @24) */
  rr=w39;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #371: @51 = @39' */
  casadi_trans(w39,casadi_s0, w51, casadi_s0, iw);
  /* #372: @50 = mac(@17,@51,@50) */
  casadi_mtimes(w17, casadi_s1, w51, casadi_s0, w50, casadi_s1, w, 0);
  /* #373: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #374: @53 = zeros(4x4) */
  casadi_clear(w53, 16);
  /* #375: @54 = zeros(4x4) */
  casadi_clear(w54, 16);
  /* #376: @8 = sin(@5) */
  w8 = sin( w5 );
  /* #377: @38 = @7[3] */
  for (rr=(&w38), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #378: @8 = (@8*@38) */
  w8 *= w38;
  /* #379: @8 = (-@8) */
  w8 = (- w8 );
  /* #380: @23 = 00 */
  /* #381: @42 = cos(@5) */
  w42 = cos( w5 );
  /* #382: @42 = (@42*@38) */
  w42 *= w38;
  /* #383: @24 = 00 */
  /* #384: @25 = horzcat(@8, @23, @42, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w42;
  /* #385: @25 = @25' */
  /* #386: @23 = zeros(4x1,0nz) */
  /* #387: @8 = cos(@5) */
  w8 = cos( w5 );
  /* #388: @8 = (@8*@38) */
  w8 *= w38;
  /* #389: @8 = (-@8) */
  w8 = (- w8 );
  /* #390: @24 = 00 */
  /* #391: @42 = sin(@5) */
  w42 = sin( w5 );
  /* #392: @42 = (@42*@38) */
  w42 *= w38;
  /* #393: @42 = (-@42) */
  w42 = (- w42 );
  /* #394: @26 = 00 */
  /* #395: @45 = horzcat(@8, @24, @42, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w42;
  /* #396: @45 = @45' */
  /* #397: @24 = zeros(4x1,0nz) */
  /* #398: @51 = horzcat(@25, @23, @45, @24) */
  rr=w51;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #399: @39 = @51' */
  casadi_trans(w51,casadi_s0, w39, casadi_s0, iw);
  /* #400: @54 = mac(@19,@39,@54) */
  casadi_mtimes(w19, casadi_s1, w39, casadi_s0, w54, casadi_s1, w, 0);
  /* #401: @53 = mac(@54,@22,@53) */
  for (i=0, rr=w53; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w54+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #402: @52 = mac(@53,@10,@52) */
  casadi_mtimes(w53, casadi_s1, w10, casadi_s0, w52, casadi_s1, w, 0);
  /* #403: @50 = (@50+@52) */
  for (i=0, rr=w50, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #404: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #405: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #406: @8 = (@8*@29) */
  w8 *= w29;
  /* #407: @8 = (-@8) */
  w8 = (- w8 );
  /* #408: @23 = 00 */
  /* #409: @42 = cos(@6) */
  w42 = cos( w6 );
  /* #410: @42 = (@42*@29) */
  w42 *= w29;
  /* #411: @24 = 00 */
  /* #412: @25 = horzcat(@8, @23, @42, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w42;
  /* #413: @25 = @25' */
  /* #414: @23 = zeros(4x1,0nz) */
  /* #415: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #416: @8 = (@8*@29) */
  w8 *= w29;
  /* #417: @8 = (-@8) */
  w8 = (- w8 );
  /* #418: @24 = 00 */
  /* #419: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #420: @6 = (@6*@29) */
  w6 *= w29;
  /* #421: @6 = (-@6) */
  w6 = (- w6 );
  /* #422: @26 = 00 */
  /* #423: @45 = horzcat(@8, @24, @6, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w6;
  /* #424: @45 = @45' */
  /* #425: @24 = zeros(4x1,0nz) */
  /* #426: @10 = horzcat(@25, @23, @45, @24) */
  rr=w10;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #427: @39 = @10' */
  casadi_trans(w10,casadi_s0, w39, casadi_s0, iw);
  /* #428: @52 = mac(@21,@39,@52) */
  casadi_mtimes(w21, casadi_s1, w39, casadi_s0, w52, casadi_s1, w, 0);
  /* #429: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #430: @54 = zeros(4x4) */
  casadi_clear(w54, 16);
  /* #431: @55 = zeros(4x4) */
  casadi_clear(w55, 16);
  /* #432: @8 = cos(@5) */
  w8 = cos( w5 );
  /* #433: @8 = (@8*@38) */
  w8 *= w38;
  /* #434: @8 = (-@8) */
  w8 = (- w8 );
  /* #435: @23 = 00 */
  /* #436: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #437: @6 = (@6*@38) */
  w6 *= w38;
  /* #438: @6 = (-@6) */
  w6 = (- w6 );
  /* #439: @24 = 00 */
  /* #440: @25 = horzcat(@8, @23, @6, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w6;
  /* #441: @25 = @25' */
  /* #442: @23 = zeros(4x1,0nz) */
  /* #443: @8 = sin(@5) */
  w8 = sin( w5 );
  /* #444: @8 = (@8*@38) */
  w8 *= w38;
  /* #445: @24 = 00 */
  /* #446: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #447: @5 = (@5*@38) */
  w5 *= w38;
  /* #448: @5 = (-@5) */
  w5 = (- w5 );
  /* #449: @26 = 00 */
  /* #450: @45 = horzcat(@8, @24, @5, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w5;
  /* #451: @45 = @45' */
  /* #452: @24 = zeros(4x1,0nz) */
  /* #453: @10 = horzcat(@25, @23, @45, @24) */
  rr=w10;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #454: @51 = @10' */
  casadi_trans(w10,casadi_s0, w51, casadi_s0, iw);
  /* #455: @55 = mac(@19,@51,@55) */
  casadi_mtimes(w19, casadi_s1, w51, casadi_s0, w55, casadi_s1, w, 0);
  /* #456: @54 = mac(@55,@22,@54) */
  for (i=0, rr=w54; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w55+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #457: @21 = mac(@54,@31,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w54+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #458: @52 = (@52+@21) */
  for (i=0, rr=w52, cs=w21; i<16; ++i) (*rr++) += (*cs++);
  /* #459: @50 = (@50+@52) */
  for (i=0, rr=w50, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #460: @2 = mac(@3,@50,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w50+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #461: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #462: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #463: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #464: @5 = @7[2] */
  for (rr=(&w5), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #465: @8 = (@8*@5) */
  w8 *= w5;
  /* #466: @8 = (-@8) */
  w8 = (- w8 );
  /* #467: @23 = 00 */
  /* #468: @38 = cos(@4) */
  w38 = cos( w4 );
  /* #469: @38 = (@38*@5) */
  w38 *= w5;
  /* #470: @24 = 00 */
  /* #471: @25 = horzcat(@8, @23, @38, @24) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w38;
  /* #472: @25 = @25' */
  /* #473: @23 = zeros(4x1,0nz) */
  /* #474: @8 = cos(@4) */
  w8 = cos( w4 );
  /* #475: @8 = (@8*@5) */
  w8 *= w5;
  /* #476: @8 = (-@8) */
  w8 = (- w8 );
  /* #477: @24 = 00 */
  /* #478: @38 = sin(@4) */
  w38 = sin( w4 );
  /* #479: @38 = (@38*@5) */
  w38 *= w5;
  /* #480: @38 = (-@38) */
  w38 = (- w38 );
  /* #481: @26 = 00 */
  /* #482: @45 = horzcat(@8, @24, @38, @26) */
  rr=w45;
  *rr++ = w8;
  *rr++ = w38;
  /* #483: @45 = @45' */
  /* #484: @24 = zeros(4x1,0nz) */
  /* #485: @51 = horzcat(@25, @23, @45, @24) */
  rr=w51;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  /* #486: @10 = @51' */
  casadi_trans(w51,casadi_s0, w10, casadi_s0, iw);
  /* #487: @52 = mac(@14,@10,@52) */
  casadi_mtimes(w14, casadi_s1, w10, casadi_s0, w52, casadi_s1, w, 0);
  /* #488: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #489: @23 = 00 */
  /* #490: @24 = 00 */
  /* #491: @26 = 00 */
  /* #492: @8 = @7[0] */
  for (rr=(&w8), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #493: @38 = horzcat(@23, @24, @26, @8) */
  rr=(&w38);
  *rr++ = w8;
  /* #494: @38 = @38' */
  /* #495: @23 = zeros(4x1,0nz) */
  /* #496: @24 = 00 */
  /* #497: @26 = 00 */
  /* #498: @32 = 00 */
  /* #499: @8 = @7[1] */
  for (rr=(&w8), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #500: @6 = horzcat(@24, @26, @32, @8) */
  rr=(&w6);
  *rr++ = w8;
  /* #501: @6 = @6' */
  /* #502: @24 = zeros(4x1,0nz) */
  /* #503: @25 = horzcat(@38, @23, @6, @24) */
  rr=w25;
  *rr++ = w38;
  *rr++ = w6;
  /* #504: @45 = @25' */
  casadi_trans(w25,casadi_s3, w45, casadi_s2, iw);
  /* #505: @21 = mac(@45,@16,@21) */
  casadi_mtimes(w45, casadi_s2, w16, casadi_s1, w21, casadi_s1, w, 0);
  /* #506: @52 = (@52+@21) */
  for (i=0, rr=w52, cs=w21; i<16; ++i) (*rr++) += (*cs++);
  /* #507: @50 = mac(@52,@13,@50) */
  for (i=0, rr=w50; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #508: @2 = (@2+@50) */
  for (i=0, rr=w2, cs=w50; i<16; ++i) (*rr++) += (*cs++);
  /* #509: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #510: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #511: @13 = mac(@17,@39,@13) */
  casadi_mtimes(w17, casadi_s1, w39, casadi_s0, w13, casadi_s1, w, 0);
  /* #512: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #513: @17 = mac(@53,@31,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w53+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #514: @13 = (@13+@17) */
  for (i=0, rr=w13, cs=w17; i<16; ++i) (*rr++) += (*cs++);
  /* #515: @50 = mac(@28,@13,@50) */
  for (i=0, rr=w50; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #516: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #517: @53 = zeros(4x4) */
  casadi_clear(w53, 16);
  /* #518: @53 = mac(@27,@10,@53) */
  casadi_mtimes(w27, casadi_s2, w10, casadi_s0, w53, casadi_s1, w, 0);
  /* #519: @17 = mac(@53,@33,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w53+j, tt=w33+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #520: @50 = (@50+@17) */
  for (i=0, rr=w50, cs=w17; i<16; ++i) (*rr++) += (*cs++);
  /* #521: @2 = (@2+@50) */
  for (i=0, rr=w2, cs=w50; i<16; ++i) (*rr++) += (*cs++);
  /* #522: @1 = mac(@2,@11,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #523: @34 = @1[:3] */
  for (rr=w34, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #524: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #525: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #526: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #527: @38 = sin(@20) */
  w38 = sin( w20 );
  /* #528: @6 = @7[6] */
  for (rr=(&w6), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #529: @38 = (@38*@6) */
  w38 *= w6;
  /* #530: @38 = (-@38) */
  w38 = (- w38 );
  /* #531: @23 = 00 */
  /* #532: @8 = cos(@20) */
  w8 = cos( w20 );
  /* #533: @8 = (@8*@6) */
  w8 *= w6;
  /* #534: @24 = 00 */
  /* #535: @27 = horzcat(@38, @23, @8, @24) */
  rr=w27;
  *rr++ = w38;
  *rr++ = w8;
  /* #536: @27 = @27' */
  /* #537: @23 = zeros(4x1,0nz) */
  /* #538: @38 = cos(@20) */
  w38 = cos( w20 );
  /* #539: @38 = (@38*@6) */
  w38 *= w6;
  /* #540: @38 = (-@38) */
  w38 = (- w38 );
  /* #541: @24 = 00 */
  /* #542: @8 = sin(@20) */
  w8 = sin( w20 );
  /* #543: @8 = (@8*@6) */
  w8 *= w6;
  /* #544: @8 = (-@8) */
  w8 = (- w8 );
  /* #545: @26 = 00 */
  /* #546: @25 = horzcat(@38, @24, @8, @26) */
  rr=w25;
  *rr++ = w38;
  *rr++ = w8;
  /* #547: @25 = @25' */
  /* #548: @24 = zeros(4x1,0nz) */
  /* #549: @10 = horzcat(@27, @23, @25, @24) */
  rr=w10;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  /* #550: @39 = @10' */
  casadi_trans(w10,casadi_s0, w39, casadi_s0, iw);
  /* #551: @50 = mac(@35,@39,@50) */
  casadi_mtimes(w35, casadi_s1, w39, casadi_s0, w50, casadi_s1, w, 0);
  /* #552: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #553: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #554: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #555: @38 = sin(@15) */
  w38 = sin( w15 );
  /* #556: @8 = @7[5] */
  for (rr=(&w8), ss=w7+5; ss!=w7+6; ss+=1) *rr++ = *ss;
  /* #557: @38 = (@38*@8) */
  w38 *= w8;
  /* #558: @38 = (-@38) */
  w38 = (- w38 );
  /* #559: @23 = 00 */
  /* #560: @29 = cos(@15) */
  w29 = cos( w15 );
  /* #561: @29 = (@29*@8) */
  w29 *= w8;
  /* #562: @24 = 00 */
  /* #563: @27 = horzcat(@38, @23, @29, @24) */
  rr=w27;
  *rr++ = w38;
  *rr++ = w29;
  /* #564: @27 = @27' */
  /* #565: @23 = zeros(4x1,0nz) */
  /* #566: @38 = cos(@15) */
  w38 = cos( w15 );
  /* #567: @38 = (@38*@8) */
  w38 *= w8;
  /* #568: @38 = (-@38) */
  w38 = (- w38 );
  /* #569: @24 = 00 */
  /* #570: @29 = sin(@15) */
  w29 = sin( w15 );
  /* #571: @29 = (@29*@8) */
  w29 *= w8;
  /* #572: @29 = (-@29) */
  w29 = (- w29 );
  /* #573: @26 = 00 */
  /* #574: @25 = horzcat(@38, @24, @29, @26) */
  rr=w25;
  *rr++ = w38;
  *rr++ = w29;
  /* #575: @25 = @25' */
  /* #576: @24 = zeros(4x1,0nz) */
  /* #577: @10 = horzcat(@27, @23, @25, @24) */
  rr=w10;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  /* #578: @51 = @10' */
  casadi_trans(w10,casadi_s0, w51, casadi_s0, iw);
  /* #579: @21 = mac(@37,@51,@21) */
  casadi_mtimes(w37, casadi_s1, w51, casadi_s0, w21, casadi_s1, w, 0);
  /* #580: @31 = mac(@21,@41,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w21+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #581: @17 = mac(@31,@40,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w31+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #582: @50 = (@50+@17) */
  for (i=0, rr=w50, cs=w17; i<16; ++i) (*rr++) += (*cs++);
  /* #583: @2 = mac(@28,@50,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w50+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #584: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #585: @28 = mac(@53,@18,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w53+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #586: @2 = (@2+@28) */
  for (i=0, rr=w2, cs=w28; i<16; ++i) (*rr++) += (*cs++);
  /* #587: @1 = mac(@2,@9,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #588: @43 = @1[:3] */
  for (rr=w43, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #589: @44 = horzcat(@34, @43) */
  rr=w44;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #590: @27 = @44[:6:3] */
  for (rr=w27, ss=w44+0; ss!=w44+6; ss+=3) *rr++ = *ss;
  /* #591: @27 = @27' */
  /* #592: @25 = @44[2:8:3] */
  for (rr=w25, ss=w44+2; ss!=w44+8; ss+=3) *rr++ = *ss;
  /* #593: @25 = @25' */
  /* #594: @1 = horzcat(@27, @25) */
  rr=w1;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  /* #595: @51 = @1' */
  for (i=0, rr=w51, cs=w1; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #596: @27 = @51[2:4] */
  for (rr=w27, ss=w51+2; ss!=w51+4; ss+=1) *rr++ = *ss;
  /* #597: (@49[:8:4] += @27) */
  for (rr=w49+0, ss=w27; rr!=w49+8; rr+=4) *rr += *ss++;
  /* #598: @27 = zeros(2x1) */
  casadi_clear(w27, 2);
  /* #599: (@49[1:9:4] = @27) */
  for (rr=w49+1, ss=w27; rr!=w49+9; rr+=4) *rr = *ss++;
  /* #600: @51 = zeros(4x1) */
  casadi_clear(w51, 4);
  /* #601: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #602: @2 = mac(@36,@13,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #603: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #604: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #605: @38 = cos(@4) */
  w38 = cos( w4 );
  /* #606: @38 = (@38*@5) */
  w38 *= w5;
  /* #607: @38 = (-@38) */
  w38 = (- w38 );
  /* #608: @23 = 00 */
  /* #609: @29 = sin(@4) */
  w29 = sin( w4 );
  /* #610: @29 = (@29*@5) */
  w29 *= w5;
  /* #611: @29 = (-@29) */
  w29 = (- w29 );
  /* #612: @24 = 00 */
  /* #613: @27 = horzcat(@38, @23, @29, @24) */
  rr=w27;
  *rr++ = w38;
  *rr++ = w29;
  /* #614: @27 = @27' */
  /* #615: @23 = zeros(4x1,0nz) */
  /* #616: @38 = sin(@4) */
  w38 = sin( w4 );
  /* #617: @38 = (@38*@5) */
  w38 *= w5;
  /* #618: @24 = 00 */
  /* #619: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #620: @4 = (@4*@5) */
  w4 *= w5;
  /* #621: @4 = (-@4) */
  w4 = (- w4 );
  /* #622: @26 = 00 */
  /* #623: @25 = horzcat(@38, @24, @4, @26) */
  rr=w25;
  *rr++ = w38;
  *rr++ = w4;
  /* #624: @25 = @25' */
  /* #625: @24 = zeros(4x1,0nz) */
  /* #626: @1 = horzcat(@27, @23, @25, @24) */
  rr=w1;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<2; ++i) *rr++ = *cs++;
  /* #627: @10 = @1' */
  casadi_trans(w1,casadi_s0, w10, casadi_s0, iw);
  /* #628: @28 = mac(@14,@10,@28) */
  casadi_mtimes(w14, casadi_s1, w10, casadi_s0, w28, casadi_s1, w, 0);
  /* #629: @14 = zeros(4x4) */
  casadi_clear(w14, 16);
  /* #630: @14 = mac(@45,@30,@14) */
  casadi_mtimes(w45, casadi_s2, w30, casadi_s0, w14, casadi_s1, w, 0);
  /* #631: @28 = (@28+@14) */
  for (i=0, rr=w28, cs=w14; i<16; ++i) (*rr++) += (*cs++);
  /* #632: @13 = mac(@28,@33,@13) */
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w33+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #633: @2 = (@2+@13) */
  for (i=0, rr=w2, cs=w13; i<16; ++i) (*rr++) += (*cs++);
  /* #634: @51 = mac(@2,@11,@51) */
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #635: @34 = @51[:3] */
  for (rr=w34, ss=w51+0; ss!=w51+3; ss+=1) *rr++ = *ss;
  /* #636: @51 = zeros(4x1) */
  casadi_clear(w51, 4);
  /* #637: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #638: @2 = mac(@36,@50,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w50+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #639: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #640: @36 = mac(@28,@18,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #641: @2 = (@2+@36) */
  for (i=0, rr=w2, cs=w36; i<16; ++i) (*rr++) += (*cs++);
  /* #642: @51 = mac(@2,@9,@51) */
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #643: @43 = @51[:3] */
  for (rr=w43, ss=w51+0; ss!=w51+3; ss+=1) *rr++ = *ss;
  /* #644: @44 = horzcat(@34, @43) */
  rr=w44;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #645: @45 = @44[:6:3] */
  for (rr=w45, ss=w44+0; ss!=w44+6; ss+=3) *rr++ = *ss;
  /* #646: @45 = @45' */
  /* #647: @27 = @44[2:8:3] */
  for (rr=w27, ss=w44+2; ss!=w44+8; ss+=3) *rr++ = *ss;
  /* #648: @27 = @27' */
  /* #649: @51 = horzcat(@45, @27) */
  rr=w51;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #650: @11 = @51' */
  for (i=0, rr=w11, cs=w51; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #651: @45 = @11[2:4] */
  for (rr=w45, ss=w11+2; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #652: (@49[1:9:4] += @45) */
  for (rr=w49+1, ss=w45; rr!=w49+9; rr+=4) *rr += *ss++;
  /* #653: @45 = zeros(2x1) */
  casadi_clear(w45, 2);
  /* #654: (@49[2:10:4] = @45) */
  for (rr=w49+2, ss=w45; rr!=w49+10; rr+=4) *rr = *ss++;
  /* #655: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #656: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #657: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #658: @36 = mac(@47,@39,@36) */
  casadi_mtimes(w47, casadi_s1, w39, casadi_s0, w36, casadi_s1, w, 0);
  /* #659: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #660: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #661: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #662: @38 = cos(@15) */
  w38 = cos( w15 );
  /* #663: @38 = (@38*@8) */
  w38 *= w8;
  /* #664: @38 = (-@38) */
  w38 = (- w38 );
  /* #665: @23 = 00 */
  /* #666: @4 = sin(@15) */
  w4 = sin( w15 );
  /* #667: @4 = (@4*@8) */
  w4 *= w8;
  /* #668: @4 = (-@4) */
  w4 = (- w4 );
  /* #669: @24 = 00 */
  /* #670: @45 = horzcat(@38, @23, @4, @24) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w4;
  /* #671: @45 = @45' */
  /* #672: @23 = zeros(4x1,0nz) */
  /* #673: @38 = sin(@15) */
  w38 = sin( w15 );
  /* #674: @38 = (@38*@8) */
  w38 *= w8;
  /* #675: @24 = 00 */
  /* #676: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #677: @15 = (@15*@8) */
  w15 *= w8;
  /* #678: @15 = (-@15) */
  w15 = (- w15 );
  /* #679: @26 = 00 */
  /* #680: @27 = horzcat(@38, @24, @15, @26) */
  rr=w27;
  *rr++ = w38;
  *rr++ = w15;
  /* #681: @27 = @27' */
  /* #682: @24 = zeros(4x1,0nz) */
  /* #683: @39 = horzcat(@45, @23, @27, @24) */
  rr=w39;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #684: @51 = @39' */
  casadi_trans(w39,casadi_s0, w51, casadi_s0, iw);
  /* #685: @18 = mac(@37,@51,@18) */
  casadi_mtimes(w37, casadi_s1, w51, casadi_s0, w18, casadi_s1, w, 0);
  /* #686: @28 = mac(@18,@41,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w41+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #687: @47 = mac(@28,@40,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #688: @36 = (@36+@47) */
  for (i=0, rr=w36, cs=w47; i<16; ++i) (*rr++) += (*cs++);
  /* #689: @2 = mac(@3,@36,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #690: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #691: @36 = mac(@52,@46,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w46+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #692: @2 = (@2+@36) */
  for (i=0, rr=w2, cs=w36; i<16; ++i) (*rr++) += (*cs++);
  /* #693: @11 = mac(@2,@9,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #694: @38 = @11[0] */
  for (rr=(&w38), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #695: @38 = @38' */
  /* #696: @15 = @11[2] */
  for (rr=(&w15), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #697: @15 = @15' */
  /* #698: @45 = horzcat(@38, @15) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w15;
  /* #699: @27 = @45' */
  casadi_trans(w45,casadi_s5, w27, casadi_s4, iw);
  /* #700: @45 = @27[:2] */
  for (rr=w45, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #701: (@49[2:10:4] += @45) */
  for (rr=w49+2, ss=w45; rr!=w49+10; rr+=4) *rr += *ss++;
  /* #702: @45 = zeros(2x1) */
  casadi_clear(w45, 2);
  /* #703: (@49[3:11:4] = @45) */
  for (rr=w49+3, ss=w45; rr!=w49+11; rr+=4) *rr = *ss++;
  /* #704: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #705: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #706: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #707: @38 = cos(@20) */
  w38 = cos( w20 );
  /* #708: @38 = (@38*@6) */
  w38 *= w6;
  /* #709: @38 = (-@38) */
  w38 = (- w38 );
  /* #710: @23 = 00 */
  /* #711: @15 = sin(@20) */
  w15 = sin( w20 );
  /* #712: @15 = (@15*@6) */
  w15 *= w6;
  /* #713: @15 = (-@15) */
  w15 = (- w15 );
  /* #714: @24 = 00 */
  /* #715: @45 = horzcat(@38, @23, @15, @24) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w15;
  /* #716: @45 = @45' */
  /* #717: @23 = zeros(4x1,0nz) */
  /* #718: @38 = sin(@20) */
  w38 = sin( w20 );
  /* #719: @38 = (@38*@6) */
  w38 *= w6;
  /* #720: @24 = 00 */
  /* #721: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #722: @20 = (@20*@6) */
  w20 *= w6;
  /* #723: @20 = (-@20) */
  w20 = (- w20 );
  /* #724: @26 = 00 */
  /* #725: @27 = horzcat(@38, @24, @20, @26) */
  rr=w27;
  *rr++ = w38;
  *rr++ = w20;
  /* #726: @27 = @27' */
  /* #727: @24 = zeros(4x1,0nz) */
  /* #728: @51 = horzcat(@45, @23, @27, @24) */
  rr=w51;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #729: @39 = @51' */
  casadi_trans(w51,casadi_s0, w39, casadi_s0, iw);
  /* #730: @36 = mac(@35,@39,@36) */
  casadi_mtimes(w35, casadi_s1, w39, casadi_s0, w36, casadi_s1, w, 0);
  /* #731: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #732: @35 = mac(@31,@12,@35) */
  casadi_mtimes(w31, casadi_s1, w12, casadi_s0, w35, casadi_s1, w, 0);
  /* #733: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<16; ++i) (*rr++) += (*cs++);
  /* #734: @2 = mac(@3,@36,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #735: @3 = zeros(4x4) */
  casadi_clear(w3, 16);
  /* #736: @3 = mac(@52,@48,@3) */
  for (i=0, rr=w3; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #737: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<16; ++i) (*rr++) += (*cs++);
  /* #738: @11 = mac(@2,@9,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #739: @38 = @11[0] */
  for (rr=(&w38), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #740: @38 = @38' */
  /* #741: @20 = @11[2] */
  for (rr=(&w20), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #742: @20 = @20' */
  /* #743: @45 = horzcat(@38, @20) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w20;
  /* #744: @27 = @45' */
  casadi_trans(w45,casadi_s5, w27, casadi_s4, iw);
  /* #745: @45 = @27[:2] */
  for (rr=w45, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #746: (@49[3:11:4] += @45) */
  for (rr=w49+3, ss=w45; rr!=w49+11; rr+=4) *rr += *ss++;
  /* #747: @0 = @49' */
  casadi_trans(w49,casadi_s7, w0, casadi_s6, iw);
  /* #748: output[1][0] = @0 */
  casadi_copy(w0, 8, res[1]);
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int BckJac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int BckJac_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int BckJac_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void BckJac_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int BckJac_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void BckJac_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void BckJac_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void BckJac_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int BckJac_n_in(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int BckJac_n_out(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real BckJac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* BckJac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* BckJac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* BckJac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* BckJac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int BckJac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 502;
  return 0;
}


