/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FrntJac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[9] = {4, 4, 0, 0, 0, 0, 2, 0, 2};
static const casadi_int casadi_s1[9] = {4, 4, 0, 1, 1, 2, 2, 3, 3};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[11] = {4, 4, 0, 2, 2, 4, 4, 0, 2, 0, 2};
static const casadi_int casadi_s4[7] = {2, 2, 0, 2, 2, 0, 1};
static const casadi_int casadi_s5[7] = {2, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s6[18] = {2, 7, 0, 1, 2, 4, 6, 8, 8, 8, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s7[13] = {7, 2, 0, 4, 8, 0, 2, 3, 4, 1, 2, 3, 4};
static const casadi_int casadi_s8[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_c0[4] = {0., 1., 0., 0.};
static const casadi_real casadi_c1[4] = {0., 0., 0., 1.};
static const casadi_real casadi_c2[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.9000000000000000e-001, 0., 0., 1.};
static const casadi_real casadi_c3[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., -2.0899999999999999e-001, 1.};
static const casadi_real casadi_c4[4] = {0., 0., -1.9500000000000001e-001, 1.};
static const casadi_real casadi_c5[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., -1.9000000000000000e-001, 0., 0., 1.};

/* FrntJac:(i0[14])->(o0[2x7,8nz],o1[2x7,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+12, *w2=w+16, *w3=w+32, w7, w8, w10, *w11=w+51, *w12=w+53, *w13=w+55, w14, w15, *w16=w+64, *w17=w+68, *w18=w+72, *w19=w+76, *w20=w+80, *w21=w+96, *w22=w+112, *w23=w+128, *w24=w+144, w25, *w26=w+161, *w27=w+177, w28, *w29=w+194, *w30=w+197, *w31=w+201, *w32=w+217, *w33=w+233, *w34=w+249, *w35=w+265, w36, *w37=w+282, *w38=w+298, *w39=w+314, *w40=w+316, w41, *w42=w+333, *w43=w+337, *w44=w+353, *w45=w+356, *w46=w+362, *w47=w+378, *w48=w+394, *w49=w+410, *w50=w+418, *w51=w+434, *w52=w+438, *w53=w+454, *w54=w+470, *w55=w+486, w56, w57, *w58=w+492, *w59=w+496, *w60=w+512, *w61=w+528, w62, *w63=w+545;
  /* #0: @0 = zeros(7x2,8nz) */
  casadi_clear(w0, 8);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #3: @3 = zeros(4x4) */
  casadi_clear(w3, 16);
  /* #4: @4 = 00 */
  /* #5: @5 = 00 */
  /* #6: @6 = 00 */
  /* #7: @7 = 1 */
  w7 = 1.;
  /* #8: @8 = horzcat(@4, @5, @6, @7) */
  rr=(&w8);
  *rr++ = w7;
  /* #9: @8 = @8' */
  /* #10: @4 = zeros(4x1,0nz) */
  /* #11: @5 = 00 */
  /* #12: @6 = 00 */
  /* #13: @9 = 00 */
  /* #14: @7 = 1 */
  w7 = 1.;
  /* #15: @10 = horzcat(@5, @6, @9, @7) */
  rr=(&w10);
  *rr++ = w7;
  /* #16: @10 = @10' */
  /* #17: @5 = zeros(4x1,0nz) */
  /* #18: @11 = horzcat(@8, @4, @10, @5) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w10;
  /* #19: @12 = @11' */
  casadi_trans(w11,casadi_s1, w12, casadi_s0, iw);
  /* #20: @13 = input[0][0] */
  casadi_copy(arg[0], 7, w13);
  /* #21: @8 = @13[2] */
  for (rr=(&w8), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #22: @10 = cos(@8) */
  w10 = cos( w8 );
  /* #23: @7 = 0 */
  w7 = 0.;
  /* #24: @14 = sin(@8) */
  w14 = sin( w8 );
  /* #25: @15 = 0 */
  w15 = 0.;
  /* #26: @16 = horzcat(@10, @7, @14, @15) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w14;
  *rr++ = w15;
  /* #27: @16 = @16' */
  /* #28: @17 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c0, 4, w17);
  /* #29: @17 = @17' */
  /* #30: @10 = sin(@8) */
  w10 = sin( w8 );
  /* #31: @10 = (-@10) */
  w10 = (- w10 );
  /* #32: @7 = 0 */
  w7 = 0.;
  /* #33: @14 = cos(@8) */
  w14 = cos( w8 );
  /* #34: @15 = 0 */
  w15 = 0.;
  /* #35: @18 = horzcat(@10, @7, @14, @15) */
  rr=w18;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w14;
  *rr++ = w15;
  /* #36: @18 = @18' */
  /* #37: @19 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w19);
  /* #38: @19 = @19' */
  /* #39: @20 = horzcat(@16, @17, @18, @19) */
  rr=w20;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #40: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #41: @3 = mac(@12,@21,@3) */
  casadi_mtimes(w12, casadi_s0, w21, casadi_s2, w3, casadi_s2, w, 0);
  /* #42: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #43: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #44: @23 = zeros(4x4) */
  casadi_clear(w23, 16);
  /* #45: @24 = 
  [[1, 0, 0, 0.19], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c2, 16, w24);
  /* #46: @10 = @13[3] */
  for (rr=(&w10), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #47: @7 = cos(@10) */
  w7 = cos( w10 );
  /* #48: @14 = 0 */
  w14 = 0.;
  /* #49: @15 = sin(@10) */
  w15 = sin( w10 );
  /* #50: @25 = 0 */
  w25 = 0.;
  /* #51: @16 = horzcat(@7, @14, @15, @25) */
  rr=w16;
  *rr++ = w7;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  /* #52: @16 = @16' */
  /* #53: @17 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c0, 4, w17);
  /* #54: @17 = @17' */
  /* #55: @7 = sin(@10) */
  w7 = sin( w10 );
  /* #56: @7 = (-@7) */
  w7 = (- w7 );
  /* #57: @14 = 0 */
  w14 = 0.;
  /* #58: @15 = cos(@10) */
  w15 = cos( w10 );
  /* #59: @25 = 0 */
  w25 = 0.;
  /* #60: @18 = horzcat(@7, @14, @15, @25) */
  rr=w18;
  *rr++ = w7;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  /* #61: @18 = @18' */
  /* #62: @19 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w19);
  /* #63: @19 = @19' */
  /* #64: @26 = horzcat(@16, @17, @18, @19) */
  rr=w26;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #65: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #66: @23 = mac(@24,@27,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #67: @27 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, -0.209], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c3, 16, w27);
  /* #68: @22 = mac(@23,@27,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #69: @7 = @13[4] */
  for (rr=(&w7), ss=w13+4; ss!=w13+5; ss+=1) *rr++ = *ss;
  /* #70: @14 = cos(@7) */
  w14 = cos( w7 );
  /* #71: @15 = 0 */
  w15 = 0.;
  /* #72: @25 = sin(@7) */
  w25 = sin( w7 );
  /* #73: @28 = 0 */
  w28 = 0.;
  /* #74: @16 = horzcat(@14, @15, @25, @28) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  /* #75: @16 = @16' */
  /* #76: @17 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c0, 4, w17);
  /* #77: @17 = @17' */
  /* #78: @14 = sin(@7) */
  w14 = sin( w7 );
  /* #79: @14 = (-@14) */
  w14 = (- w14 );
  /* #80: @15 = 0 */
  w15 = 0.;
  /* #81: @25 = cos(@7) */
  w25 = cos( w7 );
  /* #82: @28 = 0 */
  w28 = 0.;
  /* #83: @18 = horzcat(@14, @15, @25, @28) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  /* #84: @18 = @18' */
  /* #85: @19 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w19);
  /* #86: @19 = @19' */
  /* #87: @23 = horzcat(@16, @17, @18, @19) */
  rr=w23;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #88: @26 = @23' */
  for (i=0, rr=w26, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #89: @20 = mac(@22,@26,@20) */
  for (i=0, rr=w20; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w22+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #90: @2 = mac(@3,@20,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #91: @16 = [0, 0, -0.195, 1] */
  casadi_copy(casadi_c4, 4, w16);
  /* #92: @1 = mac(@2,@16,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #93: @29 = @1[:3] */
  for (rr=w29, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #94: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #95: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #96: @23 = zeros(4x4) */
  casadi_clear(w23, 16);
  /* #97: @14 = 1 */
  w14 = 1.;
  /* #98: @15 = 0 */
  w15 = 0.;
  /* #99: @25 = 0 */
  w25 = 0.;
  /* #100: @28 = @13[0] */
  for (rr=(&w28), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #101: @17 = horzcat(@14, @15, @25, @28) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  /* #102: @17 = @17' */
  /* #103: @14 = 0 */
  w14 = 0.;
  /* #104: @15 = 1 */
  w15 = 1.;
  /* #105: @25 = 0 */
  w25 = 0.;
  /* #106: @28 = 0 */
  w28 = 0.;
  /* #107: @18 = horzcat(@14, @15, @25, @28) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  /* #108: @18 = @18' */
  /* #109: @14 = 0 */
  w14 = 0.;
  /* #110: @15 = 0 */
  w15 = 0.;
  /* #111: @25 = 1 */
  w25 = 1.;
  /* #112: @28 = @13[1] */
  for (rr=(&w28), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #113: @19 = horzcat(@14, @15, @25, @28) */
  rr=w19;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  /* #114: @19 = @19' */
  /* #115: @30 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w30);
  /* #116: @30 = @30' */
  /* #117: @31 = horzcat(@17, @18, @19, @30) */
  rr=w31;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #118: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #119: @23 = mac(@32,@21,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w32+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #120: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #121: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #122: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #123: @35 = 
  [[1, 0, 0, -0.19], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 16, w35);
  /* #124: @14 = @13[5] */
  for (rr=(&w14), ss=w13+5; ss!=w13+6; ss+=1) *rr++ = *ss;
  /* #125: @15 = cos(@14) */
  w15 = cos( w14 );
  /* #126: @25 = 0 */
  w25 = 0.;
  /* #127: @28 = sin(@14) */
  w28 = sin( w14 );
  /* #128: @36 = 0 */
  w36 = 0.;
  /* #129: @17 = horzcat(@15, @25, @28, @36) */
  rr=w17;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w36;
  /* #130: @17 = @17' */
  /* #131: @18 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c0, 4, w18);
  /* #132: @18 = @18' */
  /* #133: @15 = sin(@14) */
  w15 = sin( w14 );
  /* #134: @15 = (-@15) */
  w15 = (- w15 );
  /* #135: @25 = 0 */
  w25 = 0.;
  /* #136: @28 = cos(@14) */
  w28 = cos( w14 );
  /* #137: @36 = 0 */
  w36 = 0.;
  /* #138: @19 = horzcat(@15, @25, @28, @36) */
  rr=w19;
  *rr++ = w15;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w36;
  /* #139: @19 = @19' */
  /* #140: @30 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w30);
  /* #141: @30 = @30' */
  /* #142: @37 = horzcat(@17, @18, @19, @30) */
  rr=w37;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #143: @38 = @37' */
  for (i=0, rr=w38, cs=w37; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #144: @34 = mac(@35,@38,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #145: @38 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, -0.209], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c3, 16, w38);
  /* #146: @33 = mac(@34,@38,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #147: @15 = @13[6] */
  for (rr=(&w15), ss=w13+6; ss!=w13+7; ss+=1) *rr++ = *ss;
  /* #148: @25 = sin(@15) */
  w25 = sin( w15 );
  /* #149: @25 = (-@25) */
  w25 = (- w25 );
  /* #150: @4 = 00 */
  /* #151: @28 = cos(@15) */
  w28 = cos( w15 );
  /* #152: @5 = 00 */
  /* #153: @11 = horzcat(@25, @4, @28, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #154: @11 = @11' */
  /* #155: @4 = zeros(4x1,0nz) */
  /* #156: @25 = cos(@15) */
  w25 = cos( w15 );
  /* #157: @25 = (-@25) */
  w25 = (- w25 );
  /* #158: @5 = 00 */
  /* #159: @28 = sin(@15) */
  w28 = sin( w15 );
  /* #160: @28 = (-@28) */
  w28 = (- w28 );
  /* #161: @6 = 00 */
  /* #162: @39 = horzcat(@25, @5, @28, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w28;
  /* #163: @39 = @39' */
  /* #164: @5 = zeros(4x1,0nz) */
  /* #165: @17 = horzcat(@11, @4, @39, @5) */
  rr=w17;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #166: @18 = @17' */
  casadi_trans(w17,casadi_s3, w18, casadi_s3, iw);
  /* #167: @31 = mac(@33,@18,@31) */
  casadi_mtimes(w33, casadi_s2, w18, casadi_s3, w31, casadi_s2, w, 0);
  /* #168: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #169: @37 = zeros(4x4) */
  casadi_clear(w37, 16);
  /* #170: @40 = zeros(4x4) */
  casadi_clear(w40, 16);
  /* #171: @25 = sin(@14) */
  w25 = sin( w14 );
  /* #172: @25 = (-@25) */
  w25 = (- w25 );
  /* #173: @4 = 00 */
  /* #174: @28 = cos(@14) */
  w28 = cos( w14 );
  /* #175: @5 = 00 */
  /* #176: @11 = horzcat(@25, @4, @28, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #177: @11 = @11' */
  /* #178: @4 = zeros(4x1,0nz) */
  /* #179: @25 = cos(@14) */
  w25 = cos( w14 );
  /* #180: @25 = (-@25) */
  w25 = (- w25 );
  /* #181: @5 = 00 */
  /* #182: @28 = sin(@14) */
  w28 = sin( w14 );
  /* #183: @28 = (-@28) */
  w28 = (- w28 );
  /* #184: @6 = 00 */
  /* #185: @39 = horzcat(@25, @5, @28, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w28;
  /* #186: @39 = @39' */
  /* #187: @5 = zeros(4x1,0nz) */
  /* #188: @17 = horzcat(@11, @4, @39, @5) */
  rr=w17;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #189: @19 = @17' */
  casadi_trans(w17,casadi_s3, w19, casadi_s3, iw);
  /* #190: @40 = mac(@35,@19,@40) */
  casadi_mtimes(w35, casadi_s2, w19, casadi_s3, w40, casadi_s2, w, 0);
  /* #191: @37 = mac(@40,@38,@37) */
  for (i=0, rr=w37; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w40+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #192: @25 = cos(@15) */
  w25 = cos( w15 );
  /* #193: @28 = 0 */
  w28 = 0.;
  /* #194: @36 = sin(@15) */
  w36 = sin( w15 );
  /* #195: @41 = 0 */
  w41 = 0.;
  /* #196: @19 = horzcat(@25, @28, @36, @41) */
  rr=w19;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w36;
  *rr++ = w41;
  /* #197: @19 = @19' */
  /* #198: @17 = [[0, 1, 0, 0]] */
  casadi_copy(casadi_c0, 4, w17);
  /* #199: @17 = @17' */
  /* #200: @25 = sin(@15) */
  w25 = sin( w15 );
  /* #201: @25 = (-@25) */
  w25 = (- w25 );
  /* #202: @28 = 0 */
  w28 = 0.;
  /* #203: @36 = cos(@15) */
  w36 = cos( w15 );
  /* #204: @41 = 0 */
  w41 = 0.;
  /* #205: @30 = horzcat(@25, @28, @36, @41) */
  rr=w30;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w36;
  *rr++ = w41;
  /* #206: @30 = @30' */
  /* #207: @42 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w42);
  /* #208: @42 = @42' */
  /* #209: @40 = horzcat(@19, @17, @30, @42) */
  rr=w40;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  /* #210: @43 = @40' */
  for (i=0, rr=w43, cs=w40; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #211: @34 = mac(@37,@43,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w37+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #212: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<16; ++i) (*rr++) += (*cs++);
  /* #213: @2 = mac(@23,@31,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #214: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #215: @40 = zeros(4x4) */
  casadi_clear(w40, 16);
  /* #216: @40 = mac(@33,@43,@40) */
  for (i=0, rr=w40; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w33+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #217: @34 = mac(@3,@40,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #218: @2 = (@2+@34) */
  for (i=0, rr=w2, cs=w34; i<16; ++i) (*rr++) += (*cs++);
  /* #219: @19 = [0, 0, -0.195, 1] */
  casadi_copy(casadi_c4, 4, w19);
  /* #220: @1 = mac(@2,@19,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #221: @44 = @1[:3] */
  for (rr=w44, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #222: @45 = horzcat(@29, @44) */
  rr=w45;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  /* #223: @11 = @45[:6:3] */
  for (rr=w11, ss=w45+0; ss!=w45+6; ss+=3) *rr++ = *ss;
  /* #224: @11 = @11' */
  /* #225: @39 = @45[2:8:3] */
  for (rr=w39, ss=w45+2; ss!=w45+8; ss+=3) *rr++ = *ss;
  /* #226: @39 = @39' */
  /* #227: @1 = horzcat(@11, @39) */
  rr=w1;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #228: @17 = @1' */
  for (i=0, rr=w17, cs=w1; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #229: @11 = @17[:2] */
  for (rr=w11, ss=w17+0; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #230: (@0[:8:4] = @11) */
  for (rr=w0+0, ss=w11; rr!=w0+8; rr+=4) *rr = *ss++;
  /* #231: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #232: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #233: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #234: @25 = sin(@8) */
  w25 = sin( w8 );
  /* #235: @25 = (-@25) */
  w25 = (- w25 );
  /* #236: @4 = 00 */
  /* #237: @28 = cos(@8) */
  w28 = cos( w8 );
  /* #238: @5 = 00 */
  /* #239: @11 = horzcat(@25, @4, @28, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #240: @11 = @11' */
  /* #241: @4 = zeros(4x1,0nz) */
  /* #242: @25 = cos(@8) */
  w25 = cos( w8 );
  /* #243: @25 = (-@25) */
  w25 = (- w25 );
  /* #244: @5 = 00 */
  /* #245: @28 = sin(@8) */
  w28 = sin( w8 );
  /* #246: @28 = (-@28) */
  w28 = (- w28 );
  /* #247: @6 = 00 */
  /* #248: @39 = horzcat(@25, @5, @28, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w28;
  /* #249: @39 = @39' */
  /* #250: @5 = zeros(4x1,0nz) */
  /* #251: @1 = horzcat(@11, @4, @39, @5) */
  rr=w1;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #252: @30 = @1' */
  casadi_trans(w1,casadi_s3, w30, casadi_s3, iw);
  /* #253: @34 = mac(@32,@30,@34) */
  casadi_mtimes(w32, casadi_s2, w30, casadi_s3, w34, casadi_s2, w, 0);
  /* #254: @2 = mac(@34,@20,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #255: @17 = mac(@2,@16,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #256: @29 = @17[:3] */
  for (rr=w29, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #257: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #258: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #259: @2 = mac(@34,@40,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #260: @17 = mac(@2,@19,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #261: @44 = @17[:3] */
  for (rr=w44, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #262: @45 = horzcat(@29, @44) */
  rr=w45;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  /* #263: @11 = @45[:6:3] */
  for (rr=w11, ss=w45+0; ss!=w45+6; ss+=3) *rr++ = *ss;
  /* #264: @11 = @11' */
  /* #265: @39 = @45[2:8:3] */
  for (rr=w39, ss=w45+2; ss!=w45+8; ss+=3) *rr++ = *ss;
  /* #266: @39 = @39' */
  /* #267: @17 = horzcat(@11, @39) */
  rr=w17;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #268: @1 = @17' */
  for (i=0, rr=w1, cs=w17; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #269: @11 = @1[:2] */
  for (rr=w11, ss=w1+0; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #270: (@0[1:9:4] = @11) */
  for (rr=w0+1, ss=w11; rr!=w0+9; rr+=4) *rr = *ss++;
  /* #271: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #272: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #273: @46 = zeros(4x4) */
  casadi_clear(w46, 16);
  /* #274: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #275: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #276: @25 = sin(@10) */
  w25 = sin( w10 );
  /* #277: @25 = (-@25) */
  w25 = (- w25 );
  /* #278: @4 = 00 */
  /* #279: @28 = cos(@10) */
  w28 = cos( w10 );
  /* #280: @5 = 00 */
  /* #281: @11 = horzcat(@25, @4, @28, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #282: @11 = @11' */
  /* #283: @4 = zeros(4x1,0nz) */
  /* #284: @25 = cos(@10) */
  w25 = cos( w10 );
  /* #285: @25 = (-@25) */
  w25 = (- w25 );
  /* #286: @5 = 00 */
  /* #287: @28 = sin(@10) */
  w28 = sin( w10 );
  /* #288: @28 = (-@28) */
  w28 = (- w28 );
  /* #289: @6 = 00 */
  /* #290: @39 = horzcat(@25, @5, @28, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w28;
  /* #291: @39 = @39' */
  /* #292: @5 = zeros(4x1,0nz) */
  /* #293: @17 = horzcat(@11, @4, @39, @5) */
  rr=w17;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #294: @42 = @17' */
  casadi_trans(w17,casadi_s3, w42, casadi_s3, iw);
  /* #295: @48 = mac(@24,@42,@48) */
  casadi_mtimes(w24, casadi_s2, w42, casadi_s3, w48, casadi_s2, w, 0);
  /* #296: @47 = mac(@48,@27,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w48+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #297: @46 = mac(@47,@26,@46) */
  for (i=0, rr=w46; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w47+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #298: @2 = mac(@23,@46,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w46+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #299: @1 = mac(@2,@16,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #300: @25 = @1[0] */
  for (rr=(&w25), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #301: @25 = @25' */
  /* #302: @28 = @1[2] */
  for (rr=(&w28), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #303: @28 = @28' */
  /* #304: @11 = horzcat(@25, @28) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #305: @39 = @11' */
  casadi_trans(w11,casadi_s5, w39, casadi_s4, iw);
  /* #306: @11 = @39[:2] */
  for (rr=w11, ss=w39+0; ss!=w39+2; ss+=1) *rr++ = *ss;
  /* #307: (@0[2:10:4] = @11) */
  for (rr=w0+2, ss=w11; rr!=w0+10; rr+=4) *rr = *ss++;
  /* #308: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #309: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #310: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #311: @25 = sin(@7) */
  w25 = sin( w7 );
  /* #312: @25 = (-@25) */
  w25 = (- w25 );
  /* #313: @4 = 00 */
  /* #314: @28 = cos(@7) */
  w28 = cos( w7 );
  /* #315: @5 = 00 */
  /* #316: @11 = horzcat(@25, @4, @28, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #317: @11 = @11' */
  /* #318: @4 = zeros(4x1,0nz) */
  /* #319: @25 = cos(@7) */
  w25 = cos( w7 );
  /* #320: @25 = (-@25) */
  w25 = (- w25 );
  /* #321: @5 = 00 */
  /* #322: @28 = sin(@7) */
  w28 = sin( w7 );
  /* #323: @28 = (-@28) */
  w28 = (- w28 );
  /* #324: @6 = 00 */
  /* #325: @39 = horzcat(@25, @5, @28, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w28;
  /* #326: @39 = @39' */
  /* #327: @5 = zeros(4x1,0nz) */
  /* #328: @42 = horzcat(@11, @4, @39, @5) */
  rr=w42;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #329: @17 = @42' */
  casadi_trans(w42,casadi_s3, w17, casadi_s3, iw);
  /* #330: @48 = mac(@22,@17,@48) */
  casadi_mtimes(w22, casadi_s2, w17, casadi_s3, w48, casadi_s2, w, 0);
  /* #331: @2 = mac(@23,@48,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #332: @1 = mac(@2,@16,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #333: @25 = @1[0] */
  for (rr=(&w25), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #334: @25 = @25' */
  /* #335: @28 = @1[2] */
  for (rr=(&w28), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #336: @28 = @28' */
  /* #337: @11 = horzcat(@25, @28) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w28;
  /* #338: @39 = @11' */
  casadi_trans(w11,casadi_s5, w39, casadi_s4, iw);
  /* #339: @11 = @39[:2] */
  for (rr=w11, ss=w39+0; ss!=w39+2; ss+=1) *rr++ = *ss;
  /* #340: (@0[3:11:4] = @11) */
  for (rr=w0+3, ss=w11; rr!=w0+11; rr+=4) *rr = *ss++;
  /* #341: @49 = @0' */
  casadi_trans(w0,casadi_s7, w49, casadi_s6, iw);
  /* #342: output[0][0] = @49 */
  casadi_copy(w49, 8, res[0]);
  /* #343: @49 = zeros(7x2,8nz) */
  casadi_clear(w49, 8);
  /* #344: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #345: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #346: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #347: @25 = sin(@7) */
  w25 = sin( w7 );
  /* #348: @13 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 7, w13);
  /* #349: @28 = @13[4] */
  for (rr=(&w28), ss=w13+4; ss!=w13+5; ss+=1) *rr++ = *ss;
  /* #350: @25 = (@25*@28) */
  w25 *= w28;
  /* #351: @25 = (-@25) */
  w25 = (- w25 );
  /* #352: @4 = 00 */
  /* #353: @36 = cos(@7) */
  w36 = cos( w7 );
  /* #354: @36 = (@36*@28) */
  w36 *= w28;
  /* #355: @5 = 00 */
  /* #356: @11 = horzcat(@25, @4, @36, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w36;
  /* #357: @11 = @11' */
  /* #358: @4 = zeros(4x1,0nz) */
  /* #359: @25 = cos(@7) */
  w25 = cos( w7 );
  /* #360: @25 = (@25*@28) */
  w25 *= w28;
  /* #361: @25 = (-@25) */
  w25 = (- w25 );
  /* #362: @5 = 00 */
  /* #363: @36 = sin(@7) */
  w36 = sin( w7 );
  /* #364: @36 = (@36*@28) */
  w36 *= w28;
  /* #365: @36 = (-@36) */
  w36 = (- w36 );
  /* #366: @6 = 00 */
  /* #367: @39 = horzcat(@25, @5, @36, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w36;
  /* #368: @39 = @39' */
  /* #369: @5 = zeros(4x1,0nz) */
  /* #370: @42 = horzcat(@11, @4, @39, @5) */
  rr=w42;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #371: @51 = @42' */
  casadi_trans(w42,casadi_s3, w51, casadi_s3, iw);
  /* #372: @50 = mac(@22,@51,@50) */
  casadi_mtimes(w22, casadi_s2, w51, casadi_s3, w50, casadi_s2, w, 0);
  /* #373: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #374: @53 = zeros(4x4) */
  casadi_clear(w53, 16);
  /* #375: @54 = zeros(4x4) */
  casadi_clear(w54, 16);
  /* #376: @25 = sin(@10) */
  w25 = sin( w10 );
  /* #377: @36 = @13[3] */
  for (rr=(&w36), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #378: @25 = (@25*@36) */
  w25 *= w36;
  /* #379: @25 = (-@25) */
  w25 = (- w25 );
  /* #380: @4 = 00 */
  /* #381: @41 = cos(@10) */
  w41 = cos( w10 );
  /* #382: @41 = (@41*@36) */
  w41 *= w36;
  /* #383: @5 = 00 */
  /* #384: @11 = horzcat(@25, @4, @41, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w41;
  /* #385: @11 = @11' */
  /* #386: @4 = zeros(4x1,0nz) */
  /* #387: @25 = cos(@10) */
  w25 = cos( w10 );
  /* #388: @25 = (@25*@36) */
  w25 *= w36;
  /* #389: @25 = (-@25) */
  w25 = (- w25 );
  /* #390: @5 = 00 */
  /* #391: @41 = sin(@10) */
  w41 = sin( w10 );
  /* #392: @41 = (@41*@36) */
  w41 *= w36;
  /* #393: @41 = (-@41) */
  w41 = (- w41 );
  /* #394: @6 = 00 */
  /* #395: @39 = horzcat(@25, @5, @41, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w41;
  /* #396: @39 = @39' */
  /* #397: @5 = zeros(4x1,0nz) */
  /* #398: @42 = horzcat(@11, @4, @39, @5) */
  rr=w42;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #399: @55 = @42' */
  casadi_trans(w42,casadi_s3, w55, casadi_s3, iw);
  /* #400: @54 = mac(@24,@55,@54) */
  casadi_mtimes(w24, casadi_s2, w55, casadi_s3, w54, casadi_s2, w, 0);
  /* #401: @53 = mac(@54,@27,@53) */
  for (i=0, rr=w53; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w54+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #402: @52 = mac(@53,@26,@52) */
  for (i=0, rr=w52; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w53+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #403: @50 = (@50+@52) */
  for (i=0, rr=w50, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #404: @2 = mac(@3,@50,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w50+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #405: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #406: @54 = zeros(4x4) */
  casadi_clear(w54, 16);
  /* #407: @25 = sin(@8) */
  w25 = sin( w8 );
  /* #408: @41 = @13[2] */
  for (rr=(&w41), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #409: @25 = (@25*@41) */
  w25 *= w41;
  /* #410: @25 = (-@25) */
  w25 = (- w25 );
  /* #411: @4 = 00 */
  /* #412: @56 = cos(@8) */
  w56 = cos( w8 );
  /* #413: @56 = (@56*@41) */
  w56 *= w41;
  /* #414: @5 = 00 */
  /* #415: @11 = horzcat(@25, @4, @56, @5) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w56;
  /* #416: @11 = @11' */
  /* #417: @4 = zeros(4x1,0nz) */
  /* #418: @25 = cos(@8) */
  w25 = cos( w8 );
  /* #419: @25 = (@25*@41) */
  w25 *= w41;
  /* #420: @25 = (-@25) */
  w25 = (- w25 );
  /* #421: @5 = 00 */
  /* #422: @56 = sin(@8) */
  w56 = sin( w8 );
  /* #423: @56 = (@56*@41) */
  w56 *= w41;
  /* #424: @56 = (-@56) */
  w56 = (- w56 );
  /* #425: @6 = 00 */
  /* #426: @39 = horzcat(@25, @5, @56, @6) */
  rr=w39;
  *rr++ = w25;
  *rr++ = w56;
  /* #427: @39 = @39' */
  /* #428: @5 = zeros(4x1,0nz) */
  /* #429: @55 = horzcat(@11, @4, @39, @5) */
  rr=w55;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #430: @42 = @55' */
  casadi_trans(w55,casadi_s3, w42, casadi_s3, iw);
  /* #431: @54 = mac(@12,@42,@54) */
  casadi_mtimes(w12, casadi_s0, w42, casadi_s3, w54, casadi_s2, w, 0);
  /* #432: @52 = mac(@54,@20,@52) */
  for (i=0, rr=w52; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w54+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #433: @2 = (@2+@52) */
  for (i=0, rr=w2, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #434: @1 = mac(@2,@16,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #435: @29 = @1[:3] */
  for (rr=w29, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #436: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #437: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #438: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #439: @25 = cos(@15) */
  w25 = cos( w15 );
  /* #440: @56 = @13[6] */
  for (rr=(&w56), ss=w13+6; ss!=w13+7; ss+=1) *rr++ = *ss;
  /* #441: @25 = (@25*@56) */
  w25 *= w56;
  /* #442: @25 = (-@25) */
  w25 = (- w25 );
  /* #443: @4 = 00 */
  /* #444: @57 = sin(@15) */
  w57 = sin( w15 );
  /* #445: @57 = (@57*@56) */
  w57 *= w56;
  /* #446: @57 = (-@57) */
  w57 = (- w57 );
  /* #447: @5 = 00 */
  /* #448: @12 = horzcat(@25, @4, @57, @5) */
  rr=w12;
  *rr++ = w25;
  *rr++ = w57;
  /* #449: @12 = @12' */
  /* #450: @4 = zeros(4x1,0nz) */
  /* #451: @25 = sin(@15) */
  w25 = sin( w15 );
  /* #452: @25 = (@25*@56) */
  w25 *= w56;
  /* #453: @5 = 00 */
  /* #454: @57 = cos(@15) */
  w57 = cos( w15 );
  /* #455: @57 = (@57*@56) */
  w57 *= w56;
  /* #456: @57 = (-@57) */
  w57 = (- w57 );
  /* #457: @6 = 00 */
  /* #458: @11 = horzcat(@25, @5, @57, @6) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w57;
  /* #459: @11 = @11' */
  /* #460: @5 = zeros(4x1,0nz) */
  /* #461: @55 = horzcat(@12, @4, @11, @5) */
  rr=w55;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  /* #462: @58 = @55' */
  casadi_trans(w55,casadi_s3, w58, casadi_s3, iw);
  /* #463: @52 = mac(@33,@58,@52) */
  casadi_mtimes(w33, casadi_s2, w58, casadi_s3, w52, casadi_s2, w, 0);
  /* #464: @59 = zeros(4x4) */
  casadi_clear(w59, 16);
  /* #465: @60 = zeros(4x4) */
  casadi_clear(w60, 16);
  /* #466: @61 = zeros(4x4) */
  casadi_clear(w61, 16);
  /* #467: @25 = sin(@14) */
  w25 = sin( w14 );
  /* #468: @57 = @13[5] */
  for (rr=(&w57), ss=w13+5; ss!=w13+6; ss+=1) *rr++ = *ss;
  /* #469: @25 = (@25*@57) */
  w25 *= w57;
  /* #470: @25 = (-@25) */
  w25 = (- w25 );
  /* #471: @4 = 00 */
  /* #472: @62 = cos(@14) */
  w62 = cos( w14 );
  /* #473: @62 = (@62*@57) */
  w62 *= w57;
  /* #474: @5 = 00 */
  /* #475: @12 = horzcat(@25, @4, @62, @5) */
  rr=w12;
  *rr++ = w25;
  *rr++ = w62;
  /* #476: @12 = @12' */
  /* #477: @4 = zeros(4x1,0nz) */
  /* #478: @25 = cos(@14) */
  w25 = cos( w14 );
  /* #479: @25 = (@25*@57) */
  w25 *= w57;
  /* #480: @25 = (-@25) */
  w25 = (- w25 );
  /* #481: @5 = 00 */
  /* #482: @62 = sin(@14) */
  w62 = sin( w14 );
  /* #483: @62 = (@62*@57) */
  w62 *= w57;
  /* #484: @62 = (-@62) */
  w62 = (- w62 );
  /* #485: @6 = 00 */
  /* #486: @11 = horzcat(@25, @5, @62, @6) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w62;
  /* #487: @11 = @11' */
  /* #488: @5 = zeros(4x1,0nz) */
  /* #489: @58 = horzcat(@12, @4, @11, @5) */
  rr=w58;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  /* #490: @55 = @58' */
  casadi_trans(w58,casadi_s3, w55, casadi_s3, iw);
  /* #491: @61 = mac(@35,@55,@61) */
  casadi_mtimes(w35, casadi_s2, w55, casadi_s3, w61, casadi_s2, w, 0);
  /* #492: @60 = mac(@61,@38,@60) */
  for (i=0, rr=w60; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w61+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #493: @59 = mac(@60,@18,@59) */
  casadi_mtimes(w60, casadi_s2, w18, casadi_s3, w59, casadi_s2, w, 0);
  /* #494: @52 = (@52+@59) */
  for (i=0, rr=w52, cs=w59; i<16; ++i) (*rr++) += (*cs++);
  /* #495: @59 = zeros(4x4) */
  casadi_clear(w59, 16);
  /* #496: @25 = sin(@15) */
  w25 = sin( w15 );
  /* #497: @25 = (@25*@56) */
  w25 *= w56;
  /* #498: @25 = (-@25) */
  w25 = (- w25 );
  /* #499: @4 = 00 */
  /* #500: @62 = cos(@15) */
  w62 = cos( w15 );
  /* #501: @62 = (@62*@56) */
  w62 *= w56;
  /* #502: @5 = 00 */
  /* #503: @12 = horzcat(@25, @4, @62, @5) */
  rr=w12;
  *rr++ = w25;
  *rr++ = w62;
  /* #504: @12 = @12' */
  /* #505: @4 = zeros(4x1,0nz) */
  /* #506: @25 = cos(@15) */
  w25 = cos( w15 );
  /* #507: @25 = (@25*@56) */
  w25 *= w56;
  /* #508: @25 = (-@25) */
  w25 = (- w25 );
  /* #509: @5 = 00 */
  /* #510: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #511: @15 = (@15*@56) */
  w15 *= w56;
  /* #512: @15 = (-@15) */
  w15 = (- w15 );
  /* #513: @6 = 00 */
  /* #514: @11 = horzcat(@25, @5, @15, @6) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w15;
  /* #515: @11 = @11' */
  /* #516: @5 = zeros(4x1,0nz) */
  /* #517: @18 = horzcat(@12, @4, @11, @5) */
  rr=w18;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  /* #518: @55 = @18' */
  casadi_trans(w18,casadi_s3, w55, casadi_s3, iw);
  /* #519: @59 = mac(@37,@55,@59) */
  casadi_mtimes(w37, casadi_s2, w55, casadi_s3, w59, casadi_s2, w, 0);
  /* #520: @37 = zeros(4x4) */
  casadi_clear(w37, 16);
  /* #521: @61 = zeros(4x4) */
  casadi_clear(w61, 16);
  /* #522: @63 = zeros(4x4) */
  casadi_clear(w63, 16);
  /* #523: @25 = cos(@14) */
  w25 = cos( w14 );
  /* #524: @25 = (@25*@57) */
  w25 *= w57;
  /* #525: @25 = (-@25) */
  w25 = (- w25 );
  /* #526: @4 = 00 */
  /* #527: @15 = sin(@14) */
  w15 = sin( w14 );
  /* #528: @15 = (@15*@57) */
  w15 *= w57;
  /* #529: @15 = (-@15) */
  w15 = (- w15 );
  /* #530: @5 = 00 */
  /* #531: @12 = horzcat(@25, @4, @15, @5) */
  rr=w12;
  *rr++ = w25;
  *rr++ = w15;
  /* #532: @12 = @12' */
  /* #533: @4 = zeros(4x1,0nz) */
  /* #534: @25 = sin(@14) */
  w25 = sin( w14 );
  /* #535: @25 = (@25*@57) */
  w25 *= w57;
  /* #536: @5 = 00 */
  /* #537: @14 = cos(@14) */
  w14 = cos( w14 );
  /* #538: @14 = (@14*@57) */
  w14 *= w57;
  /* #539: @14 = (-@14) */
  w14 = (- w14 );
  /* #540: @6 = 00 */
  /* #541: @11 = horzcat(@25, @5, @14, @6) */
  rr=w11;
  *rr++ = w25;
  *rr++ = w14;
  /* #542: @11 = @11' */
  /* #543: @5 = zeros(4x1,0nz) */
  /* #544: @18 = horzcat(@12, @4, @11, @5) */
  rr=w18;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  /* #545: @58 = @18' */
  casadi_trans(w18,casadi_s3, w58, casadi_s3, iw);
  /* #546: @63 = mac(@35,@58,@63) */
  casadi_mtimes(w35, casadi_s2, w58, casadi_s3, w63, casadi_s2, w, 0);
  /* #547: @61 = mac(@63,@38,@61) */
  for (i=0, rr=w61; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w63+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #548: @37 = mac(@61,@43,@37) */
  for (i=0, rr=w37; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w61+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #549: @59 = (@59+@37) */
  for (i=0, rr=w59, cs=w37; i<16; ++i) (*rr++) += (*cs++);
  /* #550: @52 = (@52+@59) */
  for (i=0, rr=w52, cs=w59; i<16; ++i) (*rr++) += (*cs++);
  /* #551: @2 = mac(@23,@52,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w52+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #552: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #553: @59 = zeros(4x4) */
  casadi_clear(w59, 16);
  /* #554: @59 = mac(@32,@42,@59) */
  casadi_mtimes(w32, casadi_s2, w42, casadi_s3, w59, casadi_s2, w, 0);
  /* #555: @37 = zeros(4x4) */
  casadi_clear(w37, 16);
  /* #556: @4 = 00 */
  /* #557: @5 = 00 */
  /* #558: @6 = 00 */
  /* #559: @25 = @13[0] */
  for (rr=(&w25), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #560: @14 = horzcat(@4, @5, @6, @25) */
  rr=(&w14);
  *rr++ = w25;
  /* #561: @14 = @14' */
  /* #562: @4 = zeros(4x1,0nz) */
  /* #563: @5 = 00 */
  /* #564: @6 = 00 */
  /* #565: @9 = 00 */
  /* #566: @25 = @13[1] */
  for (rr=(&w25), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #567: @57 = horzcat(@5, @6, @9, @25) */
  rr=(&w57);
  *rr++ = w25;
  /* #568: @57 = @57' */
  /* #569: @5 = zeros(4x1,0nz) */
  /* #570: @12 = horzcat(@14, @4, @57, @5) */
  rr=w12;
  *rr++ = w14;
  *rr++ = w57;
  /* #571: @11 = @12' */
  casadi_trans(w12,casadi_s1, w11, casadi_s0, iw);
  /* #572: @37 = mac(@11,@21,@37) */
  casadi_mtimes(w11, casadi_s0, w21, casadi_s2, w37, casadi_s2, w, 0);
  /* #573: @59 = (@59+@37) */
  for (i=0, rr=w59, cs=w37; i<16; ++i) (*rr++) += (*cs++);
  /* #574: @52 = mac(@59,@31,@52) */
  for (i=0, rr=w52; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w59+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #575: @2 = (@2+@52) */
  for (i=0, rr=w2, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #576: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #577: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #578: @31 = mac(@33,@55,@31) */
  casadi_mtimes(w33, casadi_s2, w55, casadi_s3, w31, casadi_s2, w, 0);
  /* #579: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #580: @33 = mac(@60,@43,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w60+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #581: @31 = (@31+@33) */
  for (i=0, rr=w31, cs=w33; i<16; ++i) (*rr++) += (*cs++);
  /* #582: @52 = mac(@3,@31,@52) */
  for (i=0, rr=w52; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w3+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #583: @3 = zeros(4x4) */
  casadi_clear(w3, 16);
  /* #584: @3 = mac(@54,@40,@3) */
  for (i=0, rr=w3; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w54+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #585: @52 = (@52+@3) */
  for (i=0, rr=w52, cs=w3; i<16; ++i) (*rr++) += (*cs++);
  /* #586: @2 = (@2+@52) */
  for (i=0, rr=w2, cs=w52; i<16; ++i) (*rr++) += (*cs++);
  /* #587: @1 = mac(@2,@19,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #588: @44 = @1[:3] */
  for (rr=w44, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #589: @45 = horzcat(@29, @44) */
  rr=w45;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  /* #590: @12 = @45[:6:3] */
  for (rr=w12, ss=w45+0; ss!=w45+6; ss+=3) *rr++ = *ss;
  /* #591: @12 = @12' */
  /* #592: @39 = @45[2:8:3] */
  for (rr=w39, ss=w45+2; ss!=w45+8; ss+=3) *rr++ = *ss;
  /* #593: @39 = @39' */
  /* #594: @1 = horzcat(@12, @39) */
  rr=w1;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #595: @55 = @1' */
  for (i=0, rr=w55, cs=w1; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #596: @12 = @55[:2] */
  for (rr=w12, ss=w55+0; ss!=w55+2; ss+=1) *rr++ = *ss;
  /* #597: (@49[:8:4] += @12) */
  for (rr=w49+0, ss=w12; rr!=w49+8; rr+=4) *rr += *ss++;
  /* #598: @12 = zeros(2x1) */
  casadi_clear(w12, 2);
  /* #599: (@49[1:9:4] = @12) */
  for (rr=w49+1, ss=w12; rr!=w49+9; rr+=4) *rr = *ss++;
  /* #600: @55 = zeros(4x1) */
  casadi_clear(w55, 4);
  /* #601: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #602: @2 = mac(@34,@50,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w50+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #603: @50 = zeros(4x4) */
  casadi_clear(w50, 16);
  /* #604: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #605: @14 = cos(@8) */
  w14 = cos( w8 );
  /* #606: @14 = (@14*@41) */
  w14 *= w41;
  /* #607: @14 = (-@14) */
  w14 = (- w14 );
  /* #608: @4 = 00 */
  /* #609: @57 = sin(@8) */
  w57 = sin( w8 );
  /* #610: @57 = (@57*@41) */
  w57 *= w41;
  /* #611: @57 = (-@57) */
  w57 = (- w57 );
  /* #612: @5 = 00 */
  /* #613: @12 = horzcat(@14, @4, @57, @5) */
  rr=w12;
  *rr++ = w14;
  *rr++ = w57;
  /* #614: @12 = @12' */
  /* #615: @4 = zeros(4x1,0nz) */
  /* #616: @14 = sin(@8) */
  w14 = sin( w8 );
  /* #617: @14 = (@14*@41) */
  w14 *= w41;
  /* #618: @5 = 00 */
  /* #619: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #620: @8 = (@8*@41) */
  w8 *= w41;
  /* #621: @8 = (-@8) */
  w8 = (- w8 );
  /* #622: @6 = 00 */
  /* #623: @39 = horzcat(@14, @5, @8, @6) */
  rr=w39;
  *rr++ = w14;
  *rr++ = w8;
  /* #624: @39 = @39' */
  /* #625: @5 = zeros(4x1,0nz) */
  /* #626: @1 = horzcat(@12, @4, @39, @5) */
  rr=w1;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  /* #627: @42 = @1' */
  casadi_trans(w1,casadi_s3, w42, casadi_s3, iw);
  /* #628: @52 = mac(@32,@42,@52) */
  casadi_mtimes(w32, casadi_s2, w42, casadi_s3, w52, casadi_s2, w, 0);
  /* #629: @32 = zeros(4x4) */
  casadi_clear(w32, 16);
  /* #630: @32 = mac(@11,@30,@32) */
  casadi_mtimes(w11, casadi_s0, w30, casadi_s3, w32, casadi_s2, w, 0);
  /* #631: @52 = (@52+@32) */
  for (i=0, rr=w52, cs=w32; i<16; ++i) (*rr++) += (*cs++);
  /* #632: @50 = mac(@52,@20,@50) */
  for (i=0, rr=w50; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #633: @2 = (@2+@50) */
  for (i=0, rr=w2, cs=w50; i<16; ++i) (*rr++) += (*cs++);
  /* #634: @55 = mac(@2,@16,@55) */
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #635: @29 = @55[:3] */
  for (rr=w29, ss=w55+0; ss!=w55+3; ss+=1) *rr++ = *ss;
  /* #636: @55 = zeros(4x1) */
  casadi_clear(w55, 4);
  /* #637: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #638: @2 = mac(@34,@31,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #639: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #640: @34 = mac(@52,@40,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w40+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #641: @2 = (@2+@34) */
  for (i=0, rr=w2, cs=w34; i<16; ++i) (*rr++) += (*cs++);
  /* #642: @55 = mac(@2,@19,@55) */
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #643: @44 = @55[:3] */
  for (rr=w44, ss=w55+0; ss!=w55+3; ss+=1) *rr++ = *ss;
  /* #644: @45 = horzcat(@29, @44) */
  rr=w45;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  /* #645: @11 = @45[:6:3] */
  for (rr=w11, ss=w45+0; ss!=w45+6; ss+=3) *rr++ = *ss;
  /* #646: @11 = @11' */
  /* #647: @12 = @45[2:8:3] */
  for (rr=w12, ss=w45+2; ss!=w45+8; ss+=3) *rr++ = *ss;
  /* #648: @12 = @12' */
  /* #649: @55 = horzcat(@11, @12) */
  rr=w55;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  /* #650: @19 = @55' */
  for (i=0, rr=w19, cs=w55; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #651: @11 = @19[:2] */
  for (rr=w11, ss=w19+0; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #652: (@49[1:9:4] += @11) */
  for (rr=w49+1, ss=w11; rr!=w49+9; rr+=4) *rr += *ss++;
  /* #653: @11 = zeros(2x1) */
  casadi_clear(w11, 2);
  /* #654: (@49[2:10:4] = @11) */
  for (rr=w49+2, ss=w11; rr!=w49+10; rr+=4) *rr = *ss++;
  /* #655: @19 = zeros(4x1) */
  casadi_clear(w19, 4);
  /* #656: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #657: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #658: @34 = mac(@47,@51,@34) */
  casadi_mtimes(w47, casadi_s2, w51, casadi_s3, w34, casadi_s2, w, 0);
  /* #659: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #660: @52 = zeros(4x4) */
  casadi_clear(w52, 16);
  /* #661: @40 = zeros(4x4) */
  casadi_clear(w40, 16);
  /* #662: @14 = cos(@10) */
  w14 = cos( w10 );
  /* #663: @14 = (@14*@36) */
  w14 *= w36;
  /* #664: @14 = (-@14) */
  w14 = (- w14 );
  /* #665: @4 = 00 */
  /* #666: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #667: @8 = (@8*@36) */
  w8 *= w36;
  /* #668: @8 = (-@8) */
  w8 = (- w8 );
  /* #669: @5 = 00 */
  /* #670: @11 = horzcat(@14, @4, @8, @5) */
  rr=w11;
  *rr++ = w14;
  *rr++ = w8;
  /* #671: @11 = @11' */
  /* #672: @4 = zeros(4x1,0nz) */
  /* #673: @14 = sin(@10) */
  w14 = sin( w10 );
  /* #674: @14 = (@14*@36) */
  w14 *= w36;
  /* #675: @5 = 00 */
  /* #676: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #677: @10 = (@10*@36) */
  w10 *= w36;
  /* #678: @10 = (-@10) */
  w10 = (- w10 );
  /* #679: @6 = 00 */
  /* #680: @12 = horzcat(@14, @5, @10, @6) */
  rr=w12;
  *rr++ = w14;
  *rr++ = w10;
  /* #681: @12 = @12' */
  /* #682: @5 = zeros(4x1,0nz) */
  /* #683: @51 = horzcat(@11, @4, @12, @5) */
  rr=w51;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  /* #684: @55 = @51' */
  casadi_trans(w51,casadi_s3, w55, casadi_s3, iw);
  /* #685: @40 = mac(@24,@55,@40) */
  casadi_mtimes(w24, casadi_s2, w55, casadi_s3, w40, casadi_s2, w, 0);
  /* #686: @52 = mac(@40,@27,@52) */
  for (i=0, rr=w52; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w40+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #687: @47 = mac(@52,@26,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w52+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #688: @34 = (@34+@47) */
  for (i=0, rr=w34, cs=w47; i<16; ++i) (*rr++) += (*cs++);
  /* #689: @2 = mac(@23,@34,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w34+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #690: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #691: @34 = mac(@59,@46,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w59+j, tt=w46+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #692: @2 = (@2+@34) */
  for (i=0, rr=w2, cs=w34; i<16; ++i) (*rr++) += (*cs++);
  /* #693: @19 = mac(@2,@16,@19) */
  for (i=0, rr=w19; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #694: @14 = @19[0] */
  for (rr=(&w14), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #695: @14 = @14' */
  /* #696: @10 = @19[2] */
  for (rr=(&w10), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #697: @10 = @10' */
  /* #698: @11 = horzcat(@14, @10) */
  rr=w11;
  *rr++ = w14;
  *rr++ = w10;
  /* #699: @12 = @11' */
  casadi_trans(w11,casadi_s5, w12, casadi_s4, iw);
  /* #700: @11 = @12[:2] */
  for (rr=w11, ss=w12+0; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #701: (@49[2:10:4] += @11) */
  for (rr=w49+2, ss=w11; rr!=w49+10; rr+=4) *rr += *ss++;
  /* #702: @11 = zeros(2x1) */
  casadi_clear(w11, 2);
  /* #703: (@49[3:11:4] = @11) */
  for (rr=w49+3, ss=w11; rr!=w49+11; rr+=4) *rr = *ss++;
  /* #704: @19 = zeros(4x1) */
  casadi_clear(w19, 4);
  /* #705: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #706: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #707: @14 = cos(@7) */
  w14 = cos( w7 );
  /* #708: @14 = (@14*@28) */
  w14 *= w28;
  /* #709: @14 = (-@14) */
  w14 = (- w14 );
  /* #710: @4 = 00 */
  /* #711: @10 = sin(@7) */
  w10 = sin( w7 );
  /* #712: @10 = (@10*@28) */
  w10 *= w28;
  /* #713: @10 = (-@10) */
  w10 = (- w10 );
  /* #714: @5 = 00 */
  /* #715: @11 = horzcat(@14, @4, @10, @5) */
  rr=w11;
  *rr++ = w14;
  *rr++ = w10;
  /* #716: @11 = @11' */
  /* #717: @4 = zeros(4x1,0nz) */
  /* #718: @14 = sin(@7) */
  w14 = sin( w7 );
  /* #719: @14 = (@14*@28) */
  w14 *= w28;
  /* #720: @5 = 00 */
  /* #721: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #722: @7 = (@7*@28) */
  w7 *= w28;
  /* #723: @7 = (-@7) */
  w7 = (- w7 );
  /* #724: @6 = 00 */
  /* #725: @12 = horzcat(@14, @5, @7, @6) */
  rr=w12;
  *rr++ = w14;
  *rr++ = w7;
  /* #726: @12 = @12' */
  /* #727: @5 = zeros(4x1,0nz) */
  /* #728: @55 = horzcat(@11, @4, @12, @5) */
  rr=w55;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  /* #729: @51 = @55' */
  casadi_trans(w55,casadi_s3, w51, casadi_s3, iw);
  /* #730: @34 = mac(@22,@51,@34) */
  casadi_mtimes(w22, casadi_s2, w51, casadi_s3, w34, casadi_s2, w, 0);
  /* #731: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #732: @22 = mac(@53,@17,@22) */
  casadi_mtimes(w53, casadi_s2, w17, casadi_s3, w22, casadi_s2, w, 0);
  /* #733: @34 = (@34+@22) */
  for (i=0, rr=w34, cs=w22; i<16; ++i) (*rr++) += (*cs++);
  /* #734: @2 = mac(@23,@34,@2) */
  for (i=0, rr=w2; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w34+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #735: @23 = zeros(4x4) */
  casadi_clear(w23, 16);
  /* #736: @23 = mac(@59,@48,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w59+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #737: @2 = (@2+@23) */
  for (i=0, rr=w2, cs=w23; i<16; ++i) (*rr++) += (*cs++);
  /* #738: @19 = mac(@2,@16,@19) */
  for (i=0, rr=w19; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w2+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #739: @14 = @19[0] */
  for (rr=(&w14), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #740: @14 = @14' */
  /* #741: @7 = @19[2] */
  for (rr=(&w7), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #742: @7 = @7' */
  /* #743: @11 = horzcat(@14, @7) */
  rr=w11;
  *rr++ = w14;
  *rr++ = w7;
  /* #744: @12 = @11' */
  casadi_trans(w11,casadi_s5, w12, casadi_s4, iw);
  /* #745: @11 = @12[:2] */
  for (rr=w11, ss=w12+0; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #746: (@49[3:11:4] += @11) */
  for (rr=w49+3, ss=w11; rr!=w49+11; rr+=4) *rr += *ss++;
  /* #747: @0 = @49' */
  casadi_trans(w49,casadi_s7, w0, casadi_s6, iw);
  /* #748: output[1][0] = @0 */
  casadi_copy(w0, 8, res[1]);
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int FrntJac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int FrntJac_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int FrntJac_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void FrntJac_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int FrntJac_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void FrntJac_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void FrntJac_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void FrntJac_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int FrntJac_n_in(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int FrntJac_n_out(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real FrntJac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* FrntJac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* FrntJac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* FrntJac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* FrntJac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int FrntJac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 561;
  return 0;
}


