/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

extern "C" int FrntJac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int FrntJac_alloc_mem(void);
extern "C" int FrntJac_init_mem(int mem);
extern "C" void FrntJac_free_mem(int mem);
extern "C" int FrntJac_checkout(void);
extern "C" void FrntJac_release(int mem);
extern "C" void FrntJac_incref(void);
extern "C" void FrntJac_decref(void);
extern "C" casadi_int FrntJac_n_out(void);
extern "C" casadi_int FrntJac_n_in(void);
extern "C" casadi_real FrntJac_default_in(casadi_int i);
extern "C" const char* FrntJac_name_in(casadi_int i);
extern "C" const char* FrntJac_name_out(casadi_int i);
extern "C" const casadi_int* FrntJac_sparsity_in(casadi_int i);
extern "C" const casadi_int* FrntJac_sparsity_out(casadi_int i);
extern "C" int FrntJac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
