/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

extern "C" int ExtMod_OutSecondMat_fn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ExtMod_OutSecondMat_fn_alloc_mem(void);
extern "C" int ExtMod_OutSecondMat_fn_init_mem(int mem);
extern "C" void ExtMod_OutSecondMat_fn_free_mem(int mem);
extern "C" int ExtMod_OutSecondMat_fn_checkout(void);
extern "C" void ExtMod_OutSecondMat_fn_release(int mem);
extern "C" void ExtMod_OutSecondMat_fn_incref(void);
extern "C" void ExtMod_OutSecondMat_fn_decref(void);
extern "C" casadi_int ExtMod_OutSecondMat_fn_n_out(void);
extern "C" casadi_int ExtMod_OutSecondMat_fn_n_in(void);
extern "C" casadi_real ExtMod_OutSecondMat_fn_default_in(casadi_int i);
extern "C" const char* ExtMod_OutSecondMat_fn_name_in(casadi_int i);
extern "C" const char* ExtMod_OutSecondMat_fn_name_out(casadi_int i);
extern "C" const casadi_int* ExtMod_OutSecondMat_fn_sparsity_in(casadi_int i);
extern "C" const casadi_int* ExtMod_OutSecondMat_fn_sparsity_out(casadi_int i);
extern "C" int ExtMod_OutSecondMat_fn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
