/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

extern "C" int KKT_x(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KKT_x_alloc_mem(void);
extern "C" int KKT_x_init_mem(int mem);
extern "C" void KKT_x_free_mem(int mem);
extern "C" int KKT_x_checkout(void);
extern "C" void KKT_x_release(int mem);
extern "C" void KKT_x_incref(void);
extern "C" void KKT_x_decref(void);
extern "C" casadi_int KKT_x_n_out(void);
extern "C" casadi_int KKT_x_n_in(void);
extern "C" casadi_real KKT_x_default_in(casadi_int i);
extern "C" const char* KKT_x_name_in(casadi_int i);
extern "C" const char* KKT_x_name_out(casadi_int i);
extern "C" const casadi_int* KKT_x_sparsity_in(casadi_int i);
extern "C" const casadi_int* KKT_x_sparsity_out(casadi_int i);
extern "C" int KKT_x_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
